"use client";

import {useEffect,useMemo,useState} from "react";
import {ArrowRight,Minus,Plus,ShoppingBag,ShoppingCart,Store,Trash2} from "lucide-react";
import AppHeader from "@/components/AppHeader";
import {getSupabase} from "@/lib/supabase";
import {DEFAULT_LANGUAGE,LANGUAGE_STORAGE_KEY,type Language} from "@/lib/i18n";

type CartGroup={storageKey:string;legacySlug:string|null;sellerId:string|null;cart:Record<number,number>};
type Card={name:string;set_code:string;collector_number:string;image_uri:string|null};
type Item={id:number;quantity:number;condition:string;finish:string;custom_price_crc:number|null;pricing_mode:string;cards:Card|null};
type Seller={id:string;public_name:string|null;slug:string};
type Group={seller:Seller|null;cart:Record<number,number>;items:Item[];sourceKeys:string[]};
const crc=new Intl.NumberFormat("es-CR",{style:"currency",currency:"CRC",maximumFractionDigits:0});
const LEGACY_PREFIX="mtg-display-cr-cart:",SELLER_PREFIX="mtg-display-cr-cart-seller:";

function mergeCart(a:Record<number,number>,b:Record<number,number>){const next={...a};for(const[id,qty]of Object.entries(b)){const key=Number(id);next[key]=Math.max(Number(next[key]||0),Number(qty||0))}return next}

export default function CartPage(){
 const[language,setLanguage]=useState<Language>(DEFAULT_LANGUAGE),[groups,setGroups]=useState<Group[]>([]),[loading,setLoading]=useState(true);const es=language==="es";
 useEffect(()=>{const stored=localStorage.getItem(LANGUAGE_STORAGE_KEY);if(stored==="es"||stored==="en")setLanguage(stored);void load()},[]);
 async function load(){const raw:CartGroup[]=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key)continue;const isStable=key.startsWith(SELLER_PREFIX),isLegacy=key.startsWith(LEGACY_PREFIX)&&!isStable;if(!isStable&&!isLegacy)continue;try{const cart=JSON.parse(localStorage.getItem(key)||"{}");if(!Object.values(cart as Record<string,number>).some(v=>Number(v)>0))continue;raw.push({storageKey:key,sellerId:isStable?key.slice(SELLER_PREFIX.length):null,legacySlug:isLegacy?key.slice(LEGACY_PREFIX.length):null,cart})}catch{}}
  if(!raw.length){setGroups([]);setLoading(false);return}const s=getSupabase();if(!s){setLoading(false);return}const resolved=new Map<string,{seller:Seller;cart:Record<number,number>;sourceKeys:string[]}>();const unresolved:Group[]=[];
  for(const g of raw){let seller:Seller|null=null;if(g.sellerId){const{data}=await s.from("profiles").select("id,public_name,slug").eq("id",g.sellerId).maybeSingle();seller=data as Seller|null}else if(g.legacySlug){const{data}=await s.from("profiles").select("id,public_name,slug").eq("slug",g.legacySlug).maybeSingle();seller=data as Seller|null}
   // Recovery for a legacy cart whose seller changed slug: inventory item IDs still
   // point to the immutable seller UUID, so infer the owner from the saved items.
   if(!seller){const ids=Object.keys(g.cart).map(Number).filter(Boolean);if(ids.length){const{data:owners}=await s.from("inventory_items").select("seller_id").in("id",ids);const ownerIds=Array.from(new Set((owners||[]).map(x=>String(x.seller_id)).filter(Boolean)));if(ownerIds.length===1){const{data}=await s.from("profiles").select("id,public_name,slug").eq("id",ownerIds[0]).maybeSingle();seller=data as Seller|null}}}
   if(!seller){unresolved.push({seller:null,cart:g.cart,items:[],sourceKeys:[g.storageKey]});continue}const existing=resolved.get(seller.id);resolved.set(seller.id,{seller,cart:mergeCart(existing?.cart||{},g.cart),sourceKeys:[...(existing?.sourceKeys||[]),g.storageKey]})}
  const result:Group[]=[];for(const entry of resolved.values()){const ids=Object.keys(entry.cart).map(Number).filter(Boolean);const{data:items}=ids.length?await s.from("inventory_items").select("id,quantity,condition,finish,pricing_mode,custom_price_crc,cards(name,set_code,collector_number,image_uri)").eq("seller_id",entry.seller.id).in("id",ids):{data:[]};const stableKey=`${SELLER_PREFIX}${entry.seller.id}`;localStorage.setItem(stableKey,JSON.stringify(entry.cart));for(const oldKey of entry.sourceKeys)if(oldKey!==stableKey)localStorage.removeItem(oldKey);result.push({seller:entry.seller,cart:entry.cart,items:(items||[]) as unknown as Item[],sourceKeys:[stableKey]})}setGroups([...result,...unresolved]);setLoading(false);window.dispatchEvent(new Event("mtg-cart-change"))}
 function save(sellerId:string,id:number,next:number){const key=`${SELLER_PREFIX}${sellerId}`,group=groups.find(g=>g.seller?.id===sellerId);if(!group)return;const cart={...group.cart};if(next<=0)delete cart[id];else cart[id]=next;if(Object.keys(cart).length)localStorage.setItem(key,JSON.stringify(cart));else localStorage.removeItem(key);setGroups(cur=>cur.map(g=>g.seller?.id===sellerId?{...g,cart,sourceKeys:[key]}:g).filter(g=>g.seller?.id!==sellerId||Object.keys(g.cart).length>0));window.dispatchEvent(new Event("mtg-cart-change"))}
 function clear(sellerId:string){const group=groups.find(g=>g.seller?.id===sellerId);for(const key of group?.sourceKeys||[])localStorage.removeItem(key);localStorage.removeItem(`${SELLER_PREFIX}${sellerId}`);setGroups(cur=>cur.filter(g=>g.seller?.id!==sellerId));window.dispatchEvent(new Event("mtg-cart-change"))}
 const count=useMemo(()=>groups.reduce((n,g)=>n+Object.values(g.cart).reduce((a,b)=>a+Number(b||0),0),0),[groups]);
 if(loading)return <main className="min-h-screen bg-background text-foreground"><AppHeader currentPath="/cart"/><div className="mx-auto max-w-6xl px-5 py-12 text-sm text-muted-foreground">{es?"Cargando carrito…":"Loading cart…"}</div></main>;
 return <main className="min-h-screen bg-background text-foreground"><AppHeader currentPath="/cart"/><div className="mx-auto max-w-6xl px-5 py-8 sm:py-12"><div className="flex flex-col gap-3 border-b border-border pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">{es?"Compras":"Shopping"}</p><h1 className="mt-2 font-serif text-4xl">{es?"Mi carrito":"My cart"}</h1><p className="mt-2 text-sm text-muted-foreground">{es?"Tus cartas están separadas por vendedor para que cada pedido sea claro y sencillo.":"Your cards are separated by seller so every order stays clear and simple."}</p></div>{count>0&&<div className="rounded-full border border-border bg-card px-4 py-2 text-sm font-semibold">{count} {count===1?(es?"carta":"card"):(es?"cartas":"cards")}</div>}</div>
 {!groups.length?<section className="mx-auto max-w-lg py-20 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-secondary text-muted-foreground"><ShoppingCart size={30}/></div><h2 className="mt-5 font-serif text-3xl">{es?"Tu carrito está vacío":"Your cart is empty"}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{es?"Explora las vitrinas y agrega las cartas que quieras comprar. Aquí las organizaremos automáticamente por vendedor.":"Explore displays and add the cards you want to buy. We'll automatically organize them here by seller."}</p><a href="/#cards" className="mt-6 inline-flex h-11 items-center gap-2 rounded-xl bg-primary px-5 font-bold text-primary-foreground"><ShoppingBag size={17}/>{es?"Explorar cartas":"Explore cards"}</a></section>:
 <div className="mt-7 space-y-5">{groups.map((g,index)=>{const slug=g.seller?.slug||"",sellerId=g.seller?.id||"",visible=g.items.filter(i=>g.cart[i.id]>0);return <section key={sellerId||index} className="overflow-hidden rounded-3xl border border-border bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 py-4"><div className="flex min-w-0 items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Store size={19}/></div><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">{es?"Vendedor":"Seller"}</p><h2 className="truncate font-semibold">{g.seller?.public_name||slug}</h2></div></div>{g.seller&&<button type="button" onClick={()=>clear(sellerId)} className="inline-flex items-center gap-1.5 text-xs font-semibold text-muted-foreground hover:text-destructive"><Trash2 size={14}/>{es?"Vaciar":"Clear"}</button>}</div>
 <div className="divide-y divide-border">{visible.length?visible.map(item=>{const qty=g.cart[item.id]||0,max=Math.max(1,item.quantity);return <div key={item.id} className="flex gap-4 p-4 sm:p-5">{item.cards?.image_uri?<img src={item.cards.image_uri} alt={item.cards.name} className="h-24 w-[69px] shrink-0 rounded-lg object-cover sm:h-28 sm:w-20"/>:<div className="h-24 w-[69px] shrink-0 rounded-lg bg-secondary sm:h-28 sm:w-20"/>}<div className="min-w-0 flex-1"><h3 className="truncate font-semibold">{item.cards?.name||"Magic card"}</h3><p className="mt-1 text-xs text-muted-foreground">{item.cards?.set_code?.toUpperCase()} #{item.cards?.collector_number} · {item.condition} · {item.finish}</p>{item.pricing_mode==="custom"&&item.custom_price_crc!=null&&<p className="mt-2 text-sm font-bold text-primary">{crc.format(Number(item.custom_price_crc))}</p>}<div className="mt-3 flex items-center gap-2"><button type="button" aria-label={es?"Reducir cantidad":"Decrease quantity"} onClick={()=>save(sellerId,item.id,qty-1)} className="grid h-8 w-8 place-items-center rounded-lg border border-border text-muted-foreground hover:text-foreground"><Minus size={14}/></button><span className="min-w-7 text-center text-sm font-bold">{qty}</span><button type="button" aria-label={es?"Aumentar cantidad":"Increase quantity"} disabled={qty>=max} onClick={()=>save(sellerId,item.id,qty+1)} className="grid h-8 w-8 place-items-center rounded-lg border border-border text-muted-foreground hover:text-foreground disabled:opacity-30"><Plus size={14}/></button><span className="ml-1 text-xs text-muted-foreground">{max} {es?"disp.":"avail."}</span><button type="button" onClick={()=>save(sellerId,item.id,0)} className="ml-auto grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-destructive/10 hover:text-destructive" aria-label={es?"Eliminar":"Remove"}><Trash2 size={15}/></button></div></div></div>}):<div className="p-5 text-sm text-muted-foreground">{es?"No pudimos recuperar las cartas de este carrito.":"We couldn't recover the cards in this cart."}</div>}</div>
 {g.seller&&<div className="flex flex-col gap-3 border-t border-border bg-secondary/20 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-muted-foreground">{es?"El pago y la entrega se coordinan por separado con cada vendedor.":"Payment and delivery are coordinated separately with each seller."}</p><a href={`/checkout/${slug}`} className="inline-flex h-10 shrink-0 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">{es?"Continuar compra":"Continue checkout"}<ArrowRight size={16}/></a></div>}</section>})}</div>}
 </div></main>
}
