"use client";

import {useEffect,useMemo,useState} from "react";
import {ArrowRight,Minus,Plus,ShoppingBag,ShoppingCart,Store,Trash2,X} from "lucide-react";
import AppHeader from "@/components/AppHeader";
import {getSupabase} from "@/lib/supabase";
import {DEFAULT_LANGUAGE,LANGUAGE_STORAGE_KEY,type Language} from "@/lib/i18n";

type CartGroup={slug:string;cart:Record<number,number>};
type Card={name:string;set_code:string;collector_number:string;image_uri:string|null};
type Item={id:number;quantity:number;condition:string;finish:string;custom_price_crc:number|null;pricing_mode:string;cards:Card|null};
type Seller={id:string;public_name:string|null;slug:string};
type Group={seller:Seller|null;cart:Record<number,number>;items:Item[]};
const crc=new Intl.NumberFormat("es-CR",{style:"currency",currency:"CRC",maximumFractionDigits:0});

export default function CartPage(){
 const[language,setLanguage]=useState<Language>(DEFAULT_LANGUAGE),[groups,setGroups]=useState<Group[]>([]),[loading,setLoading]=useState(true),[clearTarget,setClearTarget]=useState<{slug:string;name:string}|null>(null);const es=language==="es";
 useEffect(()=>{const stored=localStorage.getItem(LANGUAGE_STORAGE_KEY);if(stored==="es"||stored==="en")setLanguage(stored);void load()},[]);
 async function load(){const raw:CartGroup[]=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith("mtg-display-cr-cart:"))continue;const slug=key.slice("mtg-display-cr-cart:".length);try{const cart=JSON.parse(localStorage.getItem(key)||"{}");if(Object.values(cart as Record<string,number>).some(v=>Number(v)>0))raw.push({slug,cart})}catch{}}
  if(!raw.length){setGroups([]);setLoading(false);return}const s=getSupabase();if(!s){setLoading(false);return}const result:Group[]=[];for(const g of raw){const{data:seller}=await s.from("profiles").select("id,public_name,slug").eq("slug",g.slug).maybeSingle();if(!seller){result.push({seller:null,cart:g.cart,items:[]});continue}const ids=Object.keys(g.cart).map(Number).filter(Boolean);const{data:items}=ids.length?await s.from("inventory_items").select("id,quantity,condition,finish,pricing_mode,custom_price_crc,cards(name,set_code,collector_number,image_uri)").eq("seller_id",seller.id).in("id",ids):{data:[]};result.push({seller:seller as Seller,cart:g.cart,items:(items||[]) as unknown as Item[]})}setGroups(result);setLoading(false)}
 function save(slug:string,id:number,next:number){const key=`mtg-display-cr-cart:${slug}`,group=groups.find(g=>g.seller?.slug===slug);if(!group)return;const cart={...group.cart};if(next<=0)delete cart[id];else cart[id]=next;if(Object.keys(cart).length)localStorage.setItem(key,JSON.stringify(cart));else localStorage.removeItem(key);setGroups(cur=>cur.map(g=>g.seller?.slug===slug?{...g,cart}:g).filter(g=>g.seller?.slug!==slug||Object.keys(g.cart).length>0));window.dispatchEvent(new Event("mtg-cart-change"))}
 function clear(slug:string){localStorage.removeItem(`mtg-display-cr-cart:${slug}`);setGroups(cur=>cur.filter(g=>g.seller?.slug!==slug));setClearTarget(null);window.dispatchEvent(new Event("mtg-cart-change"))}
 const count=useMemo(()=>groups.reduce((n,g)=>n+Object.values(g.cart).reduce((a,b)=>a+Number(b||0),0),0),[groups]);
 if(loading)return <main className="min-h-screen bg-background text-foreground"><AppHeader currentPath="/cart"/><div className="mx-auto max-w-6xl px-5 py-12 text-sm text-muted-foreground">{es?"Cargando carrito…":"Loading cart…"}</div></main>;
 return <main className="min-h-screen bg-background text-foreground"><AppHeader currentPath="/cart"/><div className="mx-auto max-w-6xl px-5 py-8 sm:py-12"><div className="flex flex-col gap-3 border-b border-border pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">{es?"Compras":"Shopping"}</p><h1 className="mt-2 font-serif text-4xl">{es?"Mi carrito":"My cart"}</h1><p className="mt-2 text-sm text-muted-foreground">{es?"Tus cartas están separadas por vendedor para que cada pedido sea claro y sencillo.":"Your cards are separated by seller so every order stays clear and simple."}</p></div>{count>0&&<div className="rounded-full border border-border bg-card px-4 py-2 text-sm font-semibold">{count} {count===1?(es?"carta":"card"):(es?"cartas":"cards")}</div>}</div>
 {!groups.length?<section className="mx-auto max-w-lg py-20 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-secondary text-muted-foreground"><ShoppingCart size={30}/></div><h2 className="mt-5 font-serif text-3xl">{es?"Tu carrito está vacío":"Your cart is empty"}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{es?"Explora las vitrinas y agrega las cartas que quieras comprar. Aquí las organizaremos automáticamente por vendedor.":"Explore displays and add the cards you want to buy. We'll automatically organize them here by seller."}</p><a href="/#cards" className="mt-6 inline-flex h-11 items-center gap-2 rounded-xl bg-primary px-5 font-bold text-primary-foreground"><ShoppingBag size={17}/>{es?"Explorar cartas":"Explore cards"}</a></section>:
 <div className="mt-7 space-y-5">{groups.map((g,index)=>{const slug=g.seller?.slug||"",visible=g.items.filter(i=>g.cart[i.id]>0),sellerName=g.seller?.public_name||slug;return <section key={slug||index} className="overflow-hidden rounded-3xl border border-border bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 py-4"><div className="flex min-w-0 items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Store size={19}/></div><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">{es?"Vendedor":"Seller"}</p><h2 className="truncate font-semibold">{sellerName}</h2></div></div>{g.seller&&<button type="button" onClick={()=>setClearTarget({slug,name:sellerName})} className="inline-flex items-center gap-1.5 text-xs font-semibold text-muted-foreground hover:text-destructive"><Trash2 size={14}/>{es?"Vaciar carrito":"Clear cart"}</button>}</div>
 <div className="divide-y divide-border">{visible.length?visible.map(item=>{const qty=g.cart[item.id]||0,max=Math.max(1,item.quantity);return <div key={item.id} className="flex gap-4 p-4 sm:p-5">{item.cards?.image_uri?<img src={item.cards.image_uri} alt={item.cards.name} className="h-24 w-[69px] shrink-0 rounded-lg object-cover sm:h-28 sm:w-20"/>:<div className="h-24 w-[69px] shrink-0 rounded-lg bg-secondary sm:h-28 sm:w-20"/>}<div className="min-w-0 flex-1"><h3 className="truncate font-semibold">{item.cards?.name||"Magic card"}</h3><p className="mt-1 text-xs text-muted-foreground">{item.cards?.set_code?.toUpperCase()} #{item.cards?.collector_number} · {item.condition} · {item.finish}</p>{item.pricing_mode==="custom"&&item.custom_price_crc!=null&&<p className="mt-2 text-sm font-bold text-primary">{crc.format(Number(item.custom_price_crc))}</p>}<div className="mt-3 flex items-center gap-2"><button type="button" aria-label={es?"Reducir cantidad":"Decrease quantity"} onClick={()=>save(slug,item.id,qty-1)} className="grid h-8 w-8 place-items-center rounded-lg border border-border text-muted-foreground hover:text-foreground"><Minus size={14}/></button><span className="min-w-7 text-center text-sm font-bold">{qty}</span><button type="button" aria-label={es?"Aumentar cantidad":"Increase quantity"} disabled={qty>=max} onClick={()=>save(slug,item.id,qty+1)} className="grid h-8 w-8 place-items-center rounded-lg border border-border text-muted-foreground hover:text-foreground disabled:opacity-30"><Plus size={14}/></button><span className="ml-1 text-xs text-muted-foreground">{max} {es?"disp.":"avail."}</span><button type="button" onClick={()=>save(slug,item.id,0)} className="ml-auto grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-destructive/10 hover:text-destructive" aria-label={es?"Eliminar":"Remove"}><Trash2 size={15}/></button></div></div></div>}):<div className="p-5 text-sm text-muted-foreground">{es?"No pudimos cargar las cartas de este vendedor.":"We couldn't load this seller's cards."}</div>}</div>
 {g.seller&&<div className="flex flex-col gap-3 border-t border-border bg-secondary/20 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-muted-foreground">{es?"El pago y la entrega se coordinan por separado con cada vendedor.":"Payment and delivery are coordinated separately with each seller."}</p><a href={`/checkout/${slug}`} className="inline-flex h-10 shrink-0 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">{es?"Continuar compra":"Continue checkout"}<ArrowRight size={16}/></a></div>}</section>})}</div>}
 </div>{clearTarget&&<div className="fixed inset-0 z-[120] grid place-items-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={e=>e.currentTarget===e.target&&setClearTarget(null)}><section role="dialog" aria-modal="true" className="w-full max-w-sm rounded-3xl border border-border bg-card p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-destructive/10 text-destructive"><Trash2 size={21}/></div><button type="button" onClick={()=>setClearTarget(null)} className="grid h-9 w-9 place-items-center rounded-xl border border-border text-muted-foreground"><X size={16}/></button></div><h2 className="mt-5 font-serif text-2xl">{es?"¿Vaciar este carrito?":"Clear this cart?"}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{es?`Se eliminarán todas las cartas de ${clearTarget.name}. Esta acción no afectará tus otros carritos.`:`All cards from ${clearTarget.name} will be removed. Your other carts won't be affected.`}</p><div className="mt-6 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setClearTarget(null)} className="h-11 rounded-xl border border-border font-semibold text-muted-foreground">{es?"Cancelar":"Cancel"}</button><button type="button" onClick={()=>clear(clearTarget.slug)} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-destructive font-bold text-destructive-foreground"><Trash2 size={16}/>{es?"Vaciar carrito":"Clear cart"}</button></div></section></div>}</main>
}
