"use client";

import { useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { AlertCircle, CheckCircle2, ChevronDown, ChevronUp, FileUp, FolderOpen, LogIn, Store, UploadCloud, X } from "lucide-react";

import AppHeader from "@/components/AppHeader";
import { getSupabase, isSupabaseConfigured } from "@/lib/supabase";
import { DEFAULT_LANGUAGE, LANGUAGE_STORAGE_KEY, type Language } from "@/lib/i18n";
import { parseMoxfieldCsv, resolveBatch, type ResolvedCard } from "@/lib/moxfield";

type ImportPricingMode = "default" | "discount";
type Binder = { id: number; name: string; is_default: boolean; is_public: boolean };
type ImportSuccess = { quantity: number; binderId: number; binderName: string };
type InventorySnapshot = { id: number; scryfall_id: string; language: string; finish: string; condition: string; quantity: number };
const PREVIEW_LIMIT = 8;

export default function ImportPage() {
  const configured = isSupabaseConfigured();
  const supabase = getSupabase();
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const [preview, setPreview] = useState<ResolvedCard[]>([]);
  const [showAllPreview, setShowAllPreview] = useState(false);
  const [progress, setProgress] = useState(0);
  const [pricingMode, setPricingMode] = useState<ImportPricingMode>("default");
  const [notice, setNotice] = useState("");
  const [working, setWorking] = useState(false);
  const [language, setLanguage] = useState<Language>(DEFAULT_LANGUAGE);
  const [binders, setBinders] = useState<Binder[]>([]);
  const [selectedBinderId, setSelectedBinderId] = useState<number | null>(null);
  const [success, setSuccess] = useState<ImportSuccess | null>(null);

  const text = language === "es" ? {
    eyebrow: "Importar", title: "Importar colección", description: "Sube tu CSV de Moxfield. Validamos cada impresión antes de guardarla.", selectCsv: "Seleccionar archivo CSV", maxRows: "Máximo 1,000 filas", rowsValidated: "filas validadas", resolved: "resueltas", needReview: "requieren revisión", previewTitle: "Vista previa del CSV", previewHelp: "Revisa las cartas validadas y elige dónde quieres guardarlas.", totalQty: "cantidad total", quantity: "Cant.", showAll: "Mostrar todas", showLess: "Mostrar menos", cardsReview: "Cartas que requieren revisión", reviewHelp: "Estas cartas no serán importadas porque su impresión exacta no pudo validarse con Scryfall.", csvRow: "Fila CSV", set: "Set", collector: "Coleccionista", cardLanguage: "Idioma", finish: "Acabado", review: "Revisar", reason: "Motivo", unknownCard: "Carta desconocida", validationFailed: "No se pudo validar la impresión.", destinationTitle: "Destino de la importación", destinationHelp: "Elige el Binder donde quieres guardar estas cartas.", tradeHint: "Trade Binder: las cartas quedan disponibles para venta.", personalHint: "Binder personal: las cartas se guardan fuera de la vitrina hasta que decidas venderlas.", noBinders: "No encontramos Binders para esta cuenta.", pricingTitle: "Precio inicial", pricingHelp: "Elige cómo se calculará el precio de este lote.", defaultPricing: "Predeterminado", defaultPricingHelp: "Usa el precio de Card Kingdom correspondiente al acabado y condición.", discountPricing: "Descuento", discountPricingHelp: "Aplica el descuento configurado por el vendedor sobre Card Kingdom.", customLater: "Los precios personalizados se pueden asignar después desde Mi catálogo.", duplicateInfo: "Si una carta ya existe en este Binder con la misma impresión, idioma, acabado y condición, su cantidad se sumará automáticamente.", importCards: "Importar", cards: "cartas", loading: "Cargando importador…", supabaseRequired: "Se requiere conexión con Supabase", supabaseDescription: "El importador requiere la configuración pública de Supabase.", back: "Volver al panel", sellerImport: "Importación del vendedor", signInDescription: "Inicia sesión para importar cartas a tu inventario.", continueGoogle: "Continuar con Google", limited: "Las importaciones están limitadas a 1,000 filas.", fileError: "No se pudo leer el archivo.", importCreateError: "No se pudo crear la importación.", validated: "impresiones validadas.", successTitle: "Importación completada", successBody: "cartas fueron agregadas correctamente a", viewBinder: "Ver Binder", importAnother: "Importar otro", verifyError: "La importación se guardó, pero no pudimos verificar todo el inventario. Revisa tu Binder antes de volver a importar para evitar duplicados."
  } : {
    eyebrow: "Import", title: "Import Collection", description: "Upload your Moxfield CSV. We validate every printing before saving it.", selectCsv: "Select CSV file", maxRows: "Maximum 1,000 rows", rowsValidated: "rows validated", resolved: "resolved", needReview: "need review", previewTitle: "CSV Preview", previewHelp: "Review the validated cards and choose where you want to store them.", totalQty: "total quantity", quantity: "Qty", showAll: "Show all", showLess: "Show less", cardsReview: "Cards needing review", reviewHelp: "These cards will not be imported because their exact printing could not be validated with Scryfall.", csvRow: "CSV row", set: "Set", collector: "Collector", cardLanguage: "Language", finish: "Finish", review: "Review", reason: "Reason", unknownCard: "Unknown card", validationFailed: "Printing could not be validated.", destinationTitle: "Import destination", destinationHelp: "Choose the Binder where these cards should be stored.", tradeHint: "Trade Binder: cards are available for sale.", personalHint: "Personal Binder: cards stay out of your storefront until you decide to sell them.", noBinders: "No Binders were found for this account.", pricingTitle: "Initial pricing", pricingHelp: "Choose how this batch will be priced.", defaultPricing: "Default", defaultPricingHelp: "Uses the Card Kingdom price matching finish and condition.", discountPricing: "Discount", discountPricingHelp: "Applies your configured seller discount to the Card Kingdom price.", customLater: "Custom pricing can be assigned later from My Catalog.", duplicateInfo: "If the same printing, language, finish, and condition already exists in this Binder, its quantity is added automatically.", importCards: "Import", cards: "cards", loading: "Loading importer…", supabaseRequired: "Supabase connection required", supabaseDescription: "The importer requires the public Supabase configuration.", back: "Back to Dashboard", sellerImport: "Seller import", signInDescription: "Sign in to import cards into your inventory.", continueGoogle: "Continue with Google", limited: "Imports are limited to 1,000 rows.", fileError: "The file could not be read.", importCreateError: "The import could not be created.", validated: "printings validated.", successTitle: "Import complete", successBody: "cards were successfully added to", viewBinder: "View Binder", importAnother: "Import another", verifyError: "The import was saved, but we could not verify the full inventory. Check your Binder before importing again to avoid duplicates."
  };

  useEffect(() => { const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY); if (stored === "es" || stored === "en") setLanguage(stored); const handle = (event: Event) => { const value = (event as CustomEvent<Language>).detail; if (value === "es" || value === "en") setLanguage(value); }; window.addEventListener("mtg-language-change", handle); return () => window.removeEventListener("mtg-language-change", handle); }, []);
  useEffect(() => { if (!supabase) { setLoading(false); return; } supabase.auth.getUser().then(({ data }) => { setUser(data.user); setLoading(false); }); const { data } = supabase.auth.onAuthStateChange((_event, session) => setUser(session?.user || null)); return () => data.subscription.unsubscribe(); }, [supabase]);
  useEffect(() => { if (!supabase || !user) { setBinders([]); setSelectedBinderId(null); return; } void (async () => { const { data, error } = await supabase.from("binders").select("id,name,is_default,is_public").eq("seller_id", user.id).order("is_default", { ascending: false }).order("name"); if (error) { setNotice(error.message); return; } const rows = (data || []) as Binder[]; setBinders(rows); setSelectedBinderId((current) => current && rows.some((b) => b.id === current) ? current : rows.find((b) => b.is_default)?.id ?? rows[0]?.id ?? null); })(); }, [supabase, user]);

  const resolved = useMemo(() => preview.filter((row) => row.status === "resolved"), [preview]);
  const unresolved = useMemo(() => preview.filter((row) => row.status === "unresolved"), [preview]);
  const visibleResolved = showAllPreview ? resolved : resolved.slice(0, PREVIEW_LIMIT);
  const totalQuantity = resolved.reduce((sum, row) => sum + row.quantity, 0);
  const selectedBinder = binders.find((binder) => binder.id === selectedBinderId) || null;

  async function signIn() { if (!supabase) return; await supabase.auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${window.location.origin}/import` } }); }
  async function readFile(file: File) { setWorking(true); setNotice(""); setPreview([]); setShowAllPreview(false); setProgress(0); setSuccess(null); try { const rows = await parseMoxfieldCsv(file); if (rows.length > 1000) throw new Error(text.limited); const result = await resolveBatch(rows, setProgress); setPreview(result); setNotice(`${result.filter((row) => row.status === "resolved").length} ${text.validated}`); } catch (error) { setNotice(error instanceof Error ? error.message : text.fileError); } setWorking(false); }

  async function importCards() {
    if (!supabase || !user || !resolved.length || !selectedBinder) return;
    setWorking(true); setNotice("");
    const { data: job, error: jobError } = await supabase.from("import_jobs").insert({ seller_id: user.id, strategy: "sum", total_rows: preview.length, resolved_rows: resolved.length, unresolved_rows: unresolved.length, status: "preview" }).select("id").single();
    if (jobError || !job) { setNotice(jobError?.message || text.importCreateError); setWorking(false); return; }
    const uniqueCards = Array.from(new Map(resolved.map((row) => [row.card!.scryfall_id, row.card!])).values());
    const { error: cardError } = await supabase.from("cards").upsert(uniqueCards, { onConflict: "scryfall_id" });
    if (cardError) { setNotice(cardError.message); setWorking(false); return; }

    const expected = new Map<string, number>();
    for (const row of resolved) {
      const key = { seller_id: user.id, binder_id: selectedBinder.id, scryfall_id: row.card!.scryfall_id, language: row.language.toLowerCase(), finish: row.finish, condition: row.condition.toUpperCase() };
      const identity = `${key.scryfall_id}|${key.language}|${key.finish}|${key.condition}`;
      const { data: existing, error: existingError } = await supabase.from("inventory_items").select("id,quantity").match(key).maybeSingle();
      if (existingError) { setNotice(existingError.message); setWorking(false); return; }
      const quantity = (existing?.quantity || 0) + row.quantity;
      const payload = { ...key, quantity, available: selectedBinder.is_default, pricing_mode: pricingMode, custom_price_crc: null, updated_at: new Date().toISOString() };
      const { error: inventoryError } = existing ? await supabase.from("inventory_items").update(payload).eq("id", existing.id) : await supabase.from("inventory_items").insert(payload);
      if (inventoryError) { setNotice(inventoryError.message); setWorking(false); return; }
      expected.set(identity, quantity);
    }

    const { error: rowsError } = await supabase.from("import_rows").insert(preview.map((row) => ({ job_id: job.id, seller_id: user.id, row_number: row.rowNumber, raw_data: row, result: row.status, error: row.error || null })));
    if (rowsError) { setNotice(rowsError.message); setWorking(false); return; }
    const { error: completeError } = await supabase.from("import_jobs").update({ status: "completed" }).eq("id", job.id);
    if (completeError) { setNotice(completeError.message); setWorking(false); return; }

    const { data: persisted, error: verifyError } = await supabase.from("inventory_items").select("id,scryfall_id,language,finish,condition,quantity").eq("seller_id", user.id).eq("binder_id", selectedBinder.id).in("scryfall_id", Array.from(new Set(resolved.map((row) => row.card!.scryfall_id))));
    if (verifyError) { setNotice(`${text.verifyError} (${verifyError.message})`); setWorking(false); return; }
    const persistedMap = new Map(((persisted || []) as InventorySnapshot[]).map((item) => [`${item.scryfall_id}|${item.language.toLowerCase()}|${item.finish}|${item.condition.toUpperCase()}`, Number(item.quantity)]));
    const verified = Array.from(expected.entries()).every(([identity, quantity]) => (persistedMap.get(identity) ?? -1) >= quantity);
    if (!verified) { setNotice(text.verifyError); setWorking(false); return; }

    setSuccess({ quantity: totalQuantity, binderId: selectedBinder.id, binderName: selectedBinder.name });
    setPreview([]); setShowAllPreview(false); setProgress(0); setNotice(""); setWorking(false);
  }

  function resetImporter() { setSuccess(null); setPreview([]); setProgress(0); setNotice(""); setShowAllPreview(false); }

  if (loading) return <main className="grid min-h-screen place-items-center bg-background text-muted-foreground">{text.loading}</main>;
  if (!configured) return <main className="grid min-h-screen place-items-center bg-background p-5 text-foreground"><section className="max-w-lg rounded-3xl border border-amber-400/25 bg-amber-300/[.06] p-7"><AlertCircle className="mb-4 text-amber-300" /><h1 className="font-serif text-3xl">{text.supabaseRequired}</h1><p className="mt-3 text-muted-foreground">{text.supabaseDescription}</p><a href="/dashboard" className="mt-6 inline-flex rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground">{text.back}</a></section></main>;
  if (!user) return <main className="grid min-h-screen place-items-center bg-background p-5 text-foreground"><section className="w-full max-w-md rounded-3xl border border-border bg-card p-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-primary text-primary-foreground"><Store /></div><h1 className="mt-5 font-serif text-3xl">{text.sellerImport}</h1><p className="mt-3 text-muted-foreground">{text.signInDescription}</p><button type="button" onClick={signIn} className="mt-7 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary font-bold text-primary-foreground"><LogIn size={18} />{text.continueGoogle}</button></section></main>;

  return <main className="min-h-screen bg-background text-foreground"><AppHeader currentPath="/import" /><div className="mx-auto max-w-5xl px-5 py-8"><div className="mb-6"><p className="text-xs font-black uppercase tracking-[.16em] text-primary">{text.eyebrow}</p><h1 className="mt-2 font-serif text-4xl font-bold">{text.title}</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted-foreground">{text.description}</p></div><section className="rounded-3xl border border-border bg-card p-6"><label className="flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-secondary/40 p-5 text-center transition hover:border-primary/60"><UploadCloud className="mb-3 text-primary" size={30} /><span className="font-semibold">{text.selectCsv}</span><span className="mt-1 text-xs text-muted-foreground">{text.maxRows}</span><input type="file" accept=".csv,text/csv" className="sr-only" onChange={(e) => e.target.files?.[0] && void readFile(e.target.files[0])} /></label>{working && progress > 0 && <div className="mt-4"><div className="h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full bg-primary" style={{ width: "100%" }} /></div><p className="mt-2 text-xs text-muted-foreground">{progress} {text.rowsValidated}</p></div>}{notice && <p className="mt-4 rounded-xl border border-border bg-secondary/40 px-4 py-3 text-sm text-muted-foreground">{notice}</p>}</section>
    {preview.length > 0 && <section className="mt-6 space-y-5"><div className="rounded-3xl border border-border bg-card p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-serif text-2xl font-bold">{text.previewTitle}</h2><p className="mt-1 text-sm text-muted-foreground">{text.previewHelp}</p></div><div className="text-right text-xs text-muted-foreground"><b className="text-foreground">{resolved.length}</b> {text.resolved} · <b className="text-foreground">{unresolved.length}</b> {text.needReview}<br/><b className="text-foreground">{totalQuantity}</b> {text.totalQty}</div></div><div className="mt-5 overflow-hidden rounded-2xl border border-border">{visibleResolved.map((row) => <div key={row.rowNumber} className="flex items-center gap-3 border-b border-border p-3 last:border-0"><div className="h-14 w-10 shrink-0 overflow-hidden rounded bg-secondary">{row.card?.image_uri && <img src={row.card.image_uri} alt="" className="h-full w-full object-cover" />}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{row.card?.name}</p><p className="text-xs text-muted-foreground">{row.card?.set_code?.toUpperCase()} #{row.card?.collector_number} · {row.language} · {row.finish} · {row.condition}</p></div><span className="text-sm font-bold">{text.quantity} {row.quantity}</span></div>)}</div>{resolved.length > PREVIEW_LIMIT && <button type="button" onClick={() => setShowAllPreview(!showAllPreview)} className="mt-3 inline-flex items-center gap-1 text-sm font-bold text-primary">{showAllPreview ? <ChevronUp size={15}/> : <ChevronDown size={15}/>} {showAllPreview ? text.showLess : text.showAll}</button>}</div>
      {unresolved.length > 0 && <div className="rounded-3xl border border-amber-400/20 bg-amber-300/[.04] p-6"><h2 className="font-serif text-2xl font-bold">{text.cardsReview}</h2><p className="mt-1 text-sm text-muted-foreground">{text.reviewHelp}</p>{unresolved.map((row) => <div key={row.rowNumber} className="mt-3 rounded-xl border border-border bg-card p-4 text-sm"><b>{row.name || text.unknownCard}</b><p className="mt-1 text-xs text-muted-foreground">{text.csvRow} {row.rowNumber} · {text.set}: {row.setCode} · {text.collector}: #{row.collectorNumber}</p><p className="mt-2 text-xs text-amber-300">{text.reason}: {row.error || text.validationFailed}</p></div>)}</div>}
      <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-border bg-card p-6"><div className="flex items-center gap-3"><FolderOpen className="text-primary"/><div><h2 className="font-serif text-xl font-bold">{text.destinationTitle}</h2><p className="text-sm text-muted-foreground">{text.destinationHelp}</p></div></div><div className="mt-4 grid gap-2">{binders.map((binder) => <button key={binder.id} type="button" onClick={() => setSelectedBinderId(binder.id)} className={`rounded-2xl border p-4 text-left transition ${selectedBinderId === binder.id ? "border-primary bg-primary/10" : "border-border bg-secondary/30 hover:border-primary/50"}`}><div className="flex items-center justify-between gap-3"><strong>{binder.name}</strong>{binder.is_default && <span className="rounded-full bg-primary/15 px-2 py-1 text-[10px] font-black uppercase text-primary">Trade Binder</span>}</div><p className="mt-1 text-xs text-muted-foreground">{binder.is_default ? text.tradeHint : text.personalHint}</p></button>)}{!binders.length && <p className="text-sm text-muted-foreground">{text.noBinders}</p>}</div></div><div className="rounded-3xl border border-border bg-card p-6"><h2 className="font-serif text-xl font-bold">{text.pricingTitle}</h2><p className="mt-1 text-sm text-muted-foreground">{text.pricingHelp}</p><div className="mt-4 grid gap-2">{(["default","discount"] as ImportPricingMode[]).map((mode) => <button key={mode} type="button" onClick={() => setPricingMode(mode)} className={`rounded-2xl border p-4 text-left ${pricingMode === mode ? "border-primary bg-primary/10" : "border-border bg-secondary/30"}`}><strong>{mode === "default" ? text.defaultPricing : text.discountPricing}</strong><p className="mt-1 text-xs text-muted-foreground">{mode === "default" ? text.defaultPricingHelp : text.discountPricingHelp}</p></button>)}</div><p className="mt-4 text-xs text-muted-foreground">{text.customLater}</p><p className="mt-2 rounded-xl border border-border bg-secondary/30 p-3 text-xs text-muted-foreground">{text.duplicateInfo}</p><button type="button" onClick={importCards} disabled={working || !resolved.length || !selectedBinder} className="mt-4 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-primary font-bold text-primary-foreground disabled:opacity-40"><FileUp size={17}/>{working ? "…" : `${text.importCards} ${resolved.length} ${text.cards}`}</button></div></div></section>}
    </div>{success && <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-5 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="relative w-full max-w-md rounded-3xl border border-border bg-card p-7 text-center shadow-2xl"><button type="button" onClick={() => setSuccess(null)} className="absolute right-4 top-4 rounded-lg p-2 text-muted-foreground hover:bg-secondary" aria-label="Close"><X size={18}/></button><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-primary/10 text-primary"><CheckCircle2 size={30}/></div><h2 className="mt-4 font-serif text-3xl font-bold">{text.successTitle}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground"><b className="text-foreground">{success.quantity}</b> {text.successBody} <b className="text-foreground">{success.binderName}</b>.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><a href={`/catalog/binders?binder=${success.binderId}`} className="flex h-11 items-center justify-center rounded-xl bg-primary px-4 font-bold text-primary-foreground">{text.viewBinder}</a><button type="button" onClick={resetImporter} className="h-11 rounded-xl border border-border bg-secondary px-4 font-semibold">{text.importAnother}</button></div></div></div>}</main>;
}
