"use client";

import { useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { AlertCircle, Check, ExternalLink, LogIn, Save, Store, UserRound } from "lucide-react";
import AppHeader from "@/components/AppHeader";
import { getSupabase, isSupabaseConfigured } from "@/lib/supabase";
import { DEFAULT_LANGUAGE, LANGUAGE_STORAGE_KEY, getTranslation, type Language } from "@/lib/i18n";

type Profile={public_name:string;slug:string;whatsapp:string;location:string;delivery_text:string;published:boolean;sinpe_mobile:string};
type DeliveryPoint={id:number;network:string;location_name:string;store_name:string;sort_order:number};
type DeliveryPreference={delivery_point_id:number;role:"buyer_pickup"|"seller_dropoff"};
const blankProfile:Profile={public_name:"",slug:"",whatsapp:"",location:"",delivery_text:"",published:false,sinpe_mobile:""};

export default function ProfilePage(){
 const configured=isSupabaseConfigured(),supabase=getSupabase();
 const [user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile>(blankProfile),[points,setPoints]=useState<DeliveryPoint[]>([]);
 const [buyerPoints,setBuyerPoints]=useState<number[]>([]),[sellerPoints,setSellerPoints]=useState<number[]>([]);
 const [loading,setLoading]=useState(true),[working,setWorking]=useState(false),[notice,setNotice]=useState("");
 const [language,setLanguage]=useState<Language>(DEFAULT_LANGUAGE);const t=getTranslation(language).profile;
 useEffect(()=>{const stored=localStorage.getItem(LANGUAGE_STORAGE_KEY);if(stored==="es"||stored==="en")setLanguage(stored);const handler=(e:Event)=>{const d=(e as CustomEvent<Language>).detail;if(d==="es"||d==="en")setLanguage(d)};addEventListener("mtg-language-change",handler);return()=>removeEventListener("mtg-language-change",handler)},[]);
 useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getUser().then(({data})=>{setUser(data.user);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>data.subscription.unsubscribe()},[supabase]);
 useEffect(()=>{if(!supabase||!user)return;void Promise.all([supabase.from("profiles").select("public_name,slug,whatsapp,location,delivery_text,published,sinpe_mobile").eq("id",user.id).single(),supabase.from("delivery_points").select("id,network,location_name,store_name,sort_order").eq("active",true).order("sort_order"),supabase.from("profile_delivery_points").select("delivery_point_id,role").eq("profile_id",user.id)]).then(([p,d,r])=>{if(p.error)setNotice(p.error.message);else if(p.data)setProfile(p.data as Profile);if(d.error)setNotice(d.error.message);else setPoints((d.data||[]) as DeliveryPoint[]);if(r.error)setNotice(r.error.message);else{const rows=(r.data||[]) as DeliveryPreference[];setBuyerPoints(rows.filter(x=>x.role==="buyer_pickup").map(x=>x.delivery_point_id));setSellerPoints(rows.filter(x=>x.role==="seller_dropoff").map(x=>x.delivery_point_id))}})},[supabase,user]);
 const publicPath=useMemo(()=>profile.slug?`/v/${profile.slug}`:"",[profile.slug]);
 const groups=useMemo(()=>{const m=new Map<string,DeliveryPoint[]>();for(const p of points)m.set(p.location_name,[...(m.get(p.location_name)||[]),p]);return [...m.entries()]},[points]);
 async function signIn(){if(supabase)await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/profile`}})}
 function toggle(id:number,role:"buyer"|"seller"){const setter=role==="buyer"?setBuyerPoints:setSellerPoints;setter(cur=>cur.includes(id)?cur.filter(x=>x!==id):[...cur,id])}
 async function saveProfile(){if(!supabase||!user)return;setWorking(true);setNotice("");const normalized={...profile,slug:profile.slug.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),whatsapp:profile.whatsapp.replace(/\D/g,""),sinpe_mobile:profile.sinpe_mobile.replace(/\D/g,"")};const profileResult=await supabase.from("profiles").update({...normalized,updated_at:new Date().toISOString()}).eq("id",user.id);if(profileResult.error){setWorking(false);setNotice(profileResult.error.message);return}const del=await supabase.from("profile_delivery_points").delete().eq("profile_id",user.id);if(del.error){setWorking(false);setNotice(del.error.message);return}const rows=[...buyerPoints.map(id=>({profile_id:user.id,delivery_point_id:id,role:"buyer_pickup"})),...sellerPoints.map(id=>({profile_id:user.id,delivery_point_id:id,role:"seller_dropoff"}))];if(rows.length){const ins=await supabase.from("profile_delivery_points").insert(rows);if(ins.error){setWorking(false);setNotice(ins.error.message);return}}setProfile(normalized);setWorking(false);setNotice(t.saved)}
 const selector=(role:"buyer"|"seller")=>{const selected=role==="buyer"?buyerPoints:sellerPoints;return <div className="mt-5 space-y-3">{groups.map(([zone,stores])=><div key={zone} className="rounded-2xl border border-border bg-background p-4"><div className="mb-3 flex items-center justify-between"><strong className="text-sm">{zone}</strong><span className="text-[11px] text-muted-foreground">{stores.filter(x=>selected.includes(x.id)).length}/{stores.length}</span></div><div className="grid gap-2 sm:grid-cols-2">{stores.map(point=><button key={point.id} type="button" onClick={()=>toggle(point.id,role)} className={`flex items-center justify-between gap-3 rounded-xl border px-3 py-2.5 text-left text-sm transition ${selected.includes(point.id)?"border-primary/40 bg-primary/[.08] text-foreground":"border-border bg-card text-muted-foreground hover:text-foreground"}`}><span>{point.store_name}</span><span className={`grid h-5 w-5 shrink-0 place-items-center rounded border ${selected.includes(point.id)?"border-primary bg-primary text-primary-foreground":"border-border"}`}>{selected.includes(point.id)&&<Check size={13}/>}</span></button>)}</div></div>)}</div>};
 if(loading)return <main className="grid min-h-screen place-items-center bg-background text-muted-foreground">{t.loading}</main>;
 if(!configured)return <main className="grid min-h-screen place-items-center bg-background p-5 text-foreground"><section className="max-w-lg rounded-3xl border border-amber-400/25 bg-amber-300/[.06] p-7"><AlertCircle className="mb-4 text-amber-500"/><h1 className="font-serif text-3xl">{t.supabaseRequired}</h1></section></main>;
 if(!user)return <main className="grid min-h-screen place-items-center bg-background p-5 text-foreground"><section className="w-full max-w-md rounded-3xl border border-border bg-card p-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-primary text-primary-foreground"><UserRound/></div><h1 className="mt-5 font-serif text-3xl">{t.title}</h1><p className="mt-3 text-muted-foreground">{t.signInDescription}</p><button onClick={signIn} className="mt-7 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary font-bold text-primary-foreground"><LogIn size={18}/>{t.continueGoogle}</button></section></main>;
 return <main className="min-h-screen bg-background text-foreground"><AppHeader currentPath="/profile"/><div className="mx-auto max-w-6xl px-5 py-8"><div className="flex flex-col justify-between gap-4 border-b border-border pb-7 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">{t.account}</p><h1 className="mt-2 font-serif text-4xl">{t.title}</h1><p className="mt-2 text-muted-foreground">{t.description}</p></div>{publicPath&&<a href={publicPath} target="_blank" rel="noreferrer" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-border bg-card px-4 text-sm font-semibold text-muted-foreground"><ExternalLink size={17}/>{t.viewPublicDisplay}</a>}</div>{notice&&<div className="mt-6 rounded-2xl border border-border bg-card px-4 py-3 text-sm text-muted-foreground">{notice}</div>}
 <div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="space-y-6"><section className="rounded-3xl border border-border bg-card p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><UserRound size={20}/></div><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">{t.general}</p><h2 className="font-serif text-2xl">{t.accountInformation}</h2></div></div><div className="mt-6 grid gap-4"><label className="grid gap-1.5 text-sm text-muted-foreground">{t.publicName}<input value={profile.public_name} onChange={e=>setProfile({...profile,public_name:e.target.value})} className="h-11 rounded-xl border border-border bg-background px-4 text-foreground outline-none focus:border-primary"/></label><label className="grid gap-1.5 text-sm text-muted-foreground">{t.accountEmail}<input value={user.email||""} disabled className="h-11 rounded-xl border border-border bg-secondary/40 px-4 text-muted-foreground"/></label><label className="grid gap-1.5 text-sm text-muted-foreground">{t.whatsapp}<input value={profile.whatsapp} onChange={e=>setProfile({...profile,whatsapp:e.target.value})} placeholder="50688888888" className="h-11 rounded-xl border border-border bg-background px-4 text-foreground outline-none focus:border-primary"/></label><label className="grid gap-1.5 text-sm text-muted-foreground">{t.location}<input value={profile.location} onChange={e=>setProfile({...profile,location:e.target.value})} placeholder={t.locationPlaceholder} className="h-11 rounded-xl border border-border bg-background px-4 text-foreground outline-none focus:border-primary"/></label></div></section>
 <section className="rounded-3xl border border-border bg-card p-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">{t.buyer}</p><h2 className="mt-1 font-serif text-2xl">{t.buyingPreferences}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{t.buyerDescription}</p>{selector("buyer")}</section></div>
 <div className="space-y-6"><section className="rounded-3xl border border-border bg-card p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Store size={20}/></div><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">{t.seller}</p><h2 className="font-serif text-2xl">{t.publicDisplay}</h2></div></div><div className="mt-6 grid gap-4"><label className="grid gap-1.5 text-sm text-muted-foreground">{t.publicLink}<div className="flex h-11 rounded-xl border border-border bg-background"><span className="flex items-center border-r border-border px-3 text-muted-foreground">/v/</span><input value={profile.slug} onChange={e=>setProfile({...profile,slug:e.target.value})} className="min-w-0 flex-1 bg-transparent px-3 text-foreground outline-none"/></div></label><label className="grid gap-1.5 text-sm text-muted-foreground">{t.deliveryNote}<input value={profile.delivery_text} onChange={e=>setProfile({...profile,delivery_text:e.target.value})} placeholder={t.deliveryPlaceholder} className="h-11 rounded-xl border border-border bg-background px-4 text-foreground outline-none focus:border-primary"/></label><label className="grid gap-1.5 text-sm text-muted-foreground">{t.sinpe}<input inputMode="numeric" value={profile.sinpe_mobile} onChange={e=>setProfile({...profile,sinpe_mobile:e.target.value})} placeholder="88888888" className="h-11 rounded-xl border border-border bg-background px-4 text-foreground outline-none focus:border-primary"/><span className="text-xs">{t.sinpeDescription}</span></label><button type="button" onClick={()=>setProfile({...profile,published:!profile.published})} className={`flex items-center justify-between rounded-2xl border p-4 text-left ${profile.published?"border-primary/35 bg-primary/[.06]":"border-border bg-background"}`}><div><p className="font-semibold">{t.publishCatalog}</p><p className="mt-1 text-xs text-muted-foreground">{t.publishDescription}</p></div><span className={`grid h-6 w-6 place-items-center rounded-md border ${profile.published?"border-primary bg-primary text-primary-foreground":"border-border"}`}>{profile.published&&<Check size={15}/>}</span></button></div><div className="mt-6 border-t border-border pt-5"><p className="font-semibold">{t.deliveryLocations}</p><p className="mt-1 text-sm text-muted-foreground">{t.deliveryLocationsDescription}</p>{selector("seller")}</div></section>
 <section className="rounded-3xl border border-border bg-card p-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-muted-foreground">{t.profileStatus}</p><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">{t.publicDisplay}</span><strong className={profile.published?"text-primary":"text-muted-foreground"}>{profile.published?t.published:t.hidden}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">{t.sellerUrl}</span><strong>{profile.slug?`@${profile.slug}`:t.notConfigured}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">{t.buyerProfile}</span><strong className={buyerPoints.length?"text-primary":"text-amber-500"}>{buyerPoints.length?`${buyerPoints.length} ✓`:t.needsDelivery}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">{t.deliveryLocations}</span><strong className={sellerPoints.length?"text-primary":"text-amber-500"}>{sellerPoints.length?`${sellerPoints.length} ✓`:t.notConfigured}</strong></div></div></section></div></div>
 <div className="sticky bottom-4 mt-6 flex justify-end"><button disabled={working} onClick={()=>void saveProfile()} className="inline-flex h-12 items-center gap-2 rounded-xl bg-primary px-6 font-bold text-primary-foreground shadow-xl disabled:opacity-50"><Save size={18}/>{working?t.saving:t.save}</button></div></div></main>
}
