"use client";

import {useEffect,useMemo,useState} from "react";
import type {User} from "@supabase/supabase-js";
import {AlertCircle,Check,ChevronDown,ExternalLink,LogIn,MapPin,Save,ShoppingBag,Store,UserRound,X} from "lucide-react";
import AppHeader from "@/components/AppHeader";
import InternationalPhoneInput from "@/components/InternationalPhoneInput";
import CostaRicaLocationSelect from "@/components/CostaRicaLocationSelect";
import {getSupabase,isSupabaseConfigured} from "@/lib/supabase";
import {DEFAULT_LANGUAGE,LANGUAGE_STORAGE_KEY,getTranslation,type Language} from "@/lib/i18n";

type Profile={public_name:string;slug:string;whatsapp:string;location:string;delivery_text:string;published:boolean;sinpe_mobile:string};
type DeliveryPoint={id:number;network:string;location_name:string;store_name:string;sort_order:number};
type DeliveryPreference={delivery_point_id:number;role:"buyer_pickup"|"seller_dropoff"};
type Section="account"|"store"|"buying"|"delivery";
const blankProfile:Profile={public_name:"",slug:"",whatsapp:"",location:"",delivery_text:"",published:false,sinpe_mobile:""};

export default function ProfilePage(){
 const configured=isSupabaseConfigured(),supabase=getSupabase();
 const[user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile>(blankProfile),[points,setPoints]=useState<DeliveryPoint[]>([]),[buyerPoints,setBuyerPoints]=useState<number[]>([]),[sellerPoints,setSellerPoints]=useState<number[]>([]),[savedState,setSavedState]=useState("");
 const[openBuyerZones,setOpenBuyerZones]=useState<string[]>([]),[openSellerZones,setOpenSellerZones]=useState<string[]>([]),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[notice,setNotice]=useState(""),[language,setLanguage]=useState<Language>(DEFAULT_LANGUAGE),[section,setSection]=useState<Section>("account"),[mobileNav,setMobileNav]=useState(false);const t=getTranslation(language).profile;
 useEffect(()=>{const stored=localStorage.getItem(LANGUAGE_STORAGE_KEY);if(stored==="es"||stored==="en")setLanguage(stored);const h=(e:Event)=>{const d=(e as CustomEvent<Language>).detail;if(d==="es"||d==="en")setLanguage(d)};addEventListener("mtg-language-change",h);return()=>removeEventListener("mtg-language-change",h)},[]);
 useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getUser().then(({data})=>{setUser(data.user);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>data.subscription.unsubscribe()},[supabase]);
 useEffect(()=>{if(!supabase||!user)return;void Promise.all([supabase.from("profiles").select("public_name,slug,whatsapp,location,delivery_text,published,sinpe_mobile").eq("id",user.id).single(),supabase.from("delivery_points").select("id,network,location_name,store_name,sort_order").eq("active",true).order("sort_order"),supabase.from("profile_delivery_points").select("delivery_point_id,role").eq("profile_id",user.id)]).then(([p,d,r])=>{if(p.error)setNotice(p.error.message);else if(p.data)setProfile(p.data as Profile);if(d.error)setNotice(d.error.message);else setPoints((d.data||[]) as DeliveryPoint[]);if(r.error)setNotice(r.error.message);else{const rows=(r.data||[]) as DeliveryPreference[],b=rows.filter(x=>x.role==="buyer_pickup").map(x=>x.delivery_point_id),s=rows.filter(x=>x.role==="seller_dropoff").map(x=>x.delivery_point_id);setBuyerPoints(b);setSellerPoints(s);if(p.data)setSavedState(JSON.stringify({profile:p.data,buyer:[...b].sort(),seller:[...s].sort()}))}})},[supabase,user]);
 const currentState=useMemo(()=>JSON.stringify({profile,buyer:[...buyerPoints].sort(),seller:[...sellerPoints].sort()}),[profile,buyerPoints,sellerPoints]),dirty=!!savedState&&currentState!==savedState;
 const publicPath=useMemo(()=>profile.slug?`/v/${profile.slug}`:"",[profile.slug]);const groups=useMemo(()=>{const m=new Map<string,DeliveryPoint[]>();for(const p of points)m.set(p.location_name,[...(m.get(p.location_name)||[]),p]);return[...m.entries()]},[points]);
 const labels=language==="es"?{account:"Perfil público",store:"Tienda",buying:"Compras y recogida",delivery:"Entregas y pagos",unsaved:"Tienes cambios sin guardar. ¿Quieres descartarlos y cambiar de sección?",discard:"Descartar",save:"Guardar cambios"}:{account:"Public profile",store:"Store",buying:"Buying & pickup",delivery:"Delivery & payments",unsaved:"You have unsaved changes. Discard them and change section?",discard:"Discard",save:"Save changes"};
 const sections:{id:Section;label:string;icon:any}[]=[{id:"account",label:labels.account,icon:UserRound},{id:"store",label:labels.store,icon:Store},{id:"buying",label:labels.buying,icon:ShoppingBag},{id:"delivery",label:labels.delivery,icon:MapPin}];
 async function signIn(){if(supabase)await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/profile`}})}
 function normalizePhone(v:string){const digits=v.replace(/\D/g,"");return digits?`+${digits}`:""}function toggle(id:number,role:"buyer"|"seller"){const setter=role==="buyer"?setBuyerPoints:setSellerPoints;setter(cur=>cur.includes(id)?cur.filter(x=>x!==id):[...cur,id])}function toggleZone(zone:string,role:"buyer"|"seller"){const setter=role==="buyer"?setOpenBuyerZones:setOpenSellerZones;setter(cur=>cur.includes(zone)?cur.filter(x=>x!==zone):[...cur,zone])}function setZoneSelection(stores:DeliveryPoint[],role:"buyer"|"seller",select:boolean){const setter=role==="buyer"?setBuyerPoints:setSellerPoints,ids=stores.map(x=>x.id);setter(cur=>select?[...new Set([...cur,...ids])]:cur.filter(id=>!ids.includes(id)))}
 function restore(){if(!savedState)return;const s=JSON.parse(savedState);setProfile(s.profile);setBuyerPoints(s.buyer);setSellerPoints(s.seller);setNotice("")}
 function changeSection(next:Section){if(next===section){setMobileNav(false);return}if(dirty&&!window.confirm(labels.unsaved))return;if(dirty)restore();setSection(next);setMobileNav(false);window.scrollTo({top:0,behavior:"smooth"})}
 async function saveProfile(){if(!supabase||!user)return;setWorking(true);setNotice("");const normalized={...profile,slug:profile.slug.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),whatsapp:normalizePhone(profile.whatsapp),sinpe_mobile:normalizePhone(profile.sinpe_mobile)};const pr=await supabase.from("profiles").update({...normalized,updated_at:new Date().toISOString()}).eq("id",user.id);if(pr.error){setWorking(false);setNotice(pr.error.message);return}const del=await supabase.from("profile_delivery_points").delete().eq("profile_id",user.id);if(del.error){setWorking(false);setNotice(del.error.message);return}const rows=[...buyerPoints.map(id=>({profile_id:user.id,delivery_point_id:id,role:"buyer_pickup"})),...sellerPoints.map(id=>({profile_id:user.id,delivery_point_id:id,role:"seller_dropoff"}))];if(rows.length){const ins=await supabase.from("profile_delivery_points").insert(rows);if(ins.error){setWorking(false);setNotice(ins.error.message);return}}setProfile(normalized);setSavedState(JSON.stringify({profile:normalized,buyer:[...buyerPoints].sort(),seller:[...sellerPoints].sort()}));setWorking(false);setNotice(t.saved)}
 const selector=(role:"buyer"|"seller")=>{const selected=role==="buyer"?buyerPoints:sellerPoints,openZones=role==="buyer"?openBuyerZones:openSellerZones;return <div className="mt-5 space-y-3">{groups.map(([zone,stores])=>{const count=stores.filter(x=>selected.includes(x.id)).length,open=openZones.includes(zone),all=count===stores.length;return <div key={zone} className="overflow-hidden rounded-2xl border border-border bg-background"><button type="button" onClick={()=>toggleZone(zone,role)} className="flex w-full items-center justify-between gap-4 p-4 text-left"><div><strong className="block text-sm">{zone}</strong><span className="text-[11px] text-muted-foreground">{count}/{stores.length} {t.selectedLocations}</span></div><ChevronDown size={18} className={`transition ${open?"rotate-180":""}`}/></button>{open&&<div className="border-t border-border p-4"><div className="mb-3 flex gap-2"><button onClick={()=>setZoneSelection(stores,role,true)} disabled={all} className="rounded-lg border border-border px-3 py-1.5 text-xs disabled:opacity-40">{t.selectAll}</button><button onClick={()=>setZoneSelection(stores,role,false)} disabled={!count} className="rounded-lg border border-border px-3 py-1.5 text-xs disabled:opacity-40">{t.clearAll}</button></div><div className="grid gap-2 sm:grid-cols-2">{stores.map(p=><button key={p.id} onClick={()=>toggle(p.id,role)} className={`flex items-center justify-between rounded-xl border px-3 py-2.5 text-left text-sm ${selected.includes(p.id)?"border-primary/40 bg-primary/[.08]":"border-border bg-card"}`}><span>{p.store_name}</span>{selected.includes(p.id)&&<Check size={15} className="text-primary"/>}</button>)}</div></div>}</div>})}</div>};
 if(loading)return <main className="grid min-h-screen place-items-center bg-background text-muted-foreground">{t.loading}</main>;if(!configured)return <main className="grid min-h-screen place-items-center bg-background p-5"><AlertCircle/></main>;if(!user)return <main className="grid min-h-screen place-items-center bg-background p-5"><section className="w-full max-w-md rounded-3xl border border-border bg-card p-8 text-center"><UserRound className="mx-auto"/><h1 className="mt-5 font-serif text-3xl">{t.title}</h1><p className="mt-3 text-muted-foreground">{t.signInDescription}</p><button onClick={signIn} className="mt-7 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary font-bold text-primary-foreground"><LogIn size={18}/>{t.continueGoogle}</button></section></main>;
 const active=sections.find(x=>x.id===section)!;
 return <main className="min-h-screen bg-background text-foreground"><AppHeader currentPath="/profile"/><div className="mx-auto max-w-6xl px-4 py-7 sm:px-5"><div className="flex flex-col justify-between gap-4 border-b border-border pb-6 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">{t.account}</p><h1 className="mt-2 font-serif text-4xl">{t.title}</h1><p className="mt-2 text-muted-foreground">{t.description}</p></div>{publicPath&&<a href={publicPath} target="_blank" rel="noreferrer" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-border px-4 text-sm font-semibold"><ExternalLink size={17}/>{t.viewPublicDisplay}</a>}</div>{notice&&<div className="mt-5 rounded-xl border border-border bg-card px-4 py-3 text-sm text-muted-foreground">{notice}</div>}
 <div className="mt-6 lg:grid lg:grid-cols-[230px_minmax(0,1fr)] lg:gap-8"><aside className="hidden lg:block"><div className="sticky top-5 space-y-1">{sections.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>changeSection(item.id)} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold ${section===item.id?"bg-primary text-primary-foreground":"text-muted-foreground hover:bg-card hover:text-foreground"}`}><Icon size={18}/>{item.label}</button>})}</div></aside>
 <div className="lg:hidden"><button onClick={()=>setMobileNav(!mobileNav)} className="flex w-full items-center justify-between rounded-xl border border-border bg-card px-4 py-3 font-semibold"><span className="flex items-center gap-3">{<active.icon size={18}/>} {active.label}</span><ChevronDown size={18} className={`transition ${mobileNav?"rotate-180":""}`}/></button>{mobileNav&&<div className="mt-2 overflow-hidden rounded-xl border border-border bg-card p-2">{sections.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>changeSection(item.id)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-semibold ${section===item.id?"bg-primary/10 text-primary":"text-muted-foreground"}`}><Icon size={18}/>{item.label}</button>})}</div>}</div>
 <div className="mt-5 min-w-0 lg:mt-0">{section==="account"&&<section><h2 className="font-serif text-3xl">{labels.account}</h2><p className="mt-1 text-sm text-muted-foreground">{language==="es"?"Información visible y datos principales de tu cuenta.":"Public information and main account details."}</p><div className="mt-6 grid gap-5 max-w-2xl"><label className="grid gap-1.5 text-sm text-muted-foreground">{t.publicName}<input value={profile.public_name} onChange={e=>setProfile({...profile,public_name:e.target.value})} className="h-11 rounded-xl border border-border bg-card px-4 text-foreground outline-none focus:border-primary"/></label><label className="grid gap-1.5 text-sm text-muted-foreground">{t.accountEmail}<input value={user.email||""} disabled className="h-11 rounded-xl border border-border bg-secondary/40 px-4"/></label><label className="grid gap-1.5 text-sm text-muted-foreground">{t.whatsapp}<InternationalPhoneInput value={profile.whatsapp} onChange={v=>setProfile({...profile,whatsapp:v})} ariaLabel={t.whatsapp}/></label><div className="grid gap-1.5"><span className="text-sm text-muted-foreground">{t.location}</span><CostaRicaLocationSelect value={profile.location} onChange={v=>setProfile({...profile,location:v})} language={language}/></div></div></section>}
 {section==="store"&&<section><h2 className="font-serif text-3xl">{labels.store}</h2><p className="mt-1 text-sm text-muted-foreground">{t.publicDisplay}</p><div className="mt-6 grid max-w-2xl gap-5"><label className="grid gap-1.5 text-sm text-muted-foreground">{t.publicLink}<div className="flex h-11 rounded-xl border border-border bg-card"><span className="flex items-center border-r border-border px-3">/v/</span><input value={profile.slug} onChange={e=>setProfile({...profile,slug:e.target.value})} className="min-w-0 flex-1 bg-transparent px-3 outline-none"/></div></label><button onClick={()=>setProfile({...profile,published:!profile.published})} className={`flex items-center justify-between rounded-xl border p-4 text-left ${profile.published?"border-primary/35 bg-primary/[.06]":"border-border bg-card"}`}><div><p className="font-semibold">{t.publishCatalog}</p><p className="mt-1 text-xs text-muted-foreground">{t.publishDescription}</p></div>{profile.published&&<Check className="text-primary"/>}</button><div className="rounded-xl border border-border bg-card p-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">{t.publicDisplay}</span><strong>{profile.published?t.published:t.hidden}</strong></div><div className="mt-3 flex justify-between"><span className="text-muted-foreground">{t.sellerUrl}</span><strong>{profile.slug?`@${profile.slug}`:t.notConfigured}</strong></div></div></div></section>}
 {section==="buying"&&<section><h2 className="font-serif text-3xl">{labels.buying}</h2><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{t.buyerDescription}</p><div className="max-w-3xl">{selector("buyer")}</div></section>}
 {section==="delivery"&&<section><h2 className="font-serif text-3xl">{labels.delivery}</h2><div className="mt-6 grid max-w-3xl gap-5"><label className="grid gap-1.5 text-sm text-muted-foreground">{t.deliveryNote}<input value={profile.delivery_text} onChange={e=>setProfile({...profile,delivery_text:e.target.value})} placeholder={t.deliveryPlaceholder} className="h-11 rounded-xl border border-border bg-card px-4 outline-none focus:border-primary"/></label><label className="grid gap-1.5 text-sm text-muted-foreground">{t.sinpe}<InternationalPhoneInput value={profile.sinpe_mobile} onChange={v=>setProfile({...profile,sinpe_mobile:v})} ariaLabel={t.sinpe}/><span className="text-xs">{t.sinpeDescription}</span></label><div className="border-t border-border pt-5"><p className="font-semibold">{t.deliveryLocations}</p><p className="mt-1 text-sm text-muted-foreground">{t.deliveryLocationsDescription}</p>{selector("seller")}</div></div></section>}</div></div>
 {dirty&&<div className="sticky bottom-3 z-20 mt-8 flex justify-end"><div className="flex gap-2 rounded-2xl border border-border bg-card/95 p-2 shadow-2xl backdrop-blur"><button disabled={working} onClick={restore} className="inline-flex h-11 items-center gap-2 rounded-xl px-4 text-sm font-semibold text-muted-foreground"><X size={17}/>{labels.discard}</button><button disabled={working} onClick={()=>void saveProfile()} className="inline-flex h-11 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-primary-foreground disabled:opacity-50"><Save size={17}/>{working?t.saving:labels.save}</button></div></div>}</div></main>
}
