"use client";

import BrandLogo from "@/components/BrandLogo";
import { useEffect, useState } from "react";
import { Copy, DollarSign, LayoutDashboard, LogOut, Package, ShoppingCart, ShoppingBag, Upload, UserRound, X, Clock3 } from "lucide-react";
import LanguageSwitch from "@/components/LanguageSwitch";
import ThemeSwitch from "@/components/ThemeSwitch";
import { getSupabase } from "@/lib/supabase";
import { DEFAULT_LANGUAGE, LANGUAGE_STORAGE_KEY, getTranslation, type Language } from "@/lib/i18n";

const SELLER_ACTIONABLE_STATUSES=["inventory_confirmation","preparing_shipment","payment_submitted","paid"];
type AppMenuProps={open:boolean;onClose:()=>void;currentPath?:string;sellerName?:string|null;sellerSlug?:string|null};
export default function AppMenu({open,onClose,currentPath="",sellerName,sellerSlug}:AppMenuProps){
 const supabase=getSupabase(),[language,setLanguage]=useState<Language>(DEFAULT_LANGUAGE),[pendingBuyerActions,setPendingBuyerActions]=useState(0),[pendingSellerActions,setPendingSellerActions]=useState(0);const t=getTranslation(language);
 useEffect(()=>{const stored=window.localStorage.getItem(LANGUAGE_STORAGE_KEY);if(stored==="es"||stored==="en")setLanguage(stored);const h=(event:Event)=>{const v=(event as CustomEvent<Language>).detail;if(v==="es"||v==="en")setLanguage(v)};window.addEventListener("mtg-language-change",h);return()=>window.removeEventListener("mtg-language-change",h)},[]);
 useEffect(()=>{if(!open)return;function esc(e:KeyboardEvent){if(e.key==="Escape")onClose()}document.addEventListener("keydown",esc);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",esc);document.body.style.overflow=""}},[open,onClose]);
 useEffect(()=>{if(!open||!supabase)return;void(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return;const[buyerResult,sellerResult]=await Promise.all([supabase.from("orders").select("id",{count:"exact",head:true}).eq("buyer_id",user.id).eq("response_required_from","buyer").not("status","in","(completed,cancelled)"),supabase.from("orders").select("id",{count:"exact",head:true}).eq("seller_id",user.id).eq("response_required_from","seller").in("status",SELLER_ACTIONABLE_STATUSES)]);setPendingBuyerActions(buyerResult.count||0);setPendingSellerActions(sellerResult.count||0)})()},[open,supabase]);
 if(!open)return null;const publicPath=sellerSlug?`/v/${sellerSlug}`:null;function active(path:string){return path==="/dashboard"?currentPath==="/dashboard":currentPath.startsWith(path)}
 async function copyStoreLink(){if(!publicPath)return;const url=`${window.location.origin}${publicPath}`;try{await navigator.clipboard.writeText(url)}catch{window.prompt(t.navigation.copyStoreLink,url)}}async function signOut(){if(!supabase)return;await supabase.auth.signOut();window.location.href="/"}
 const row=(label:string,href:string,Icon:typeof LayoutDashboard,badge=0)=><a href={href} onClick={onClose} className={`mb-1 flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold transition ${active(href)?"bg-primary text-primary-foreground":"text-muted-foreground hover:bg-secondary hover:text-foreground"}`}><Icon size={18}/><span className="flex-1">{label}</span>{badge>0&&<span className="grid min-w-6 place-items-center rounded-full bg-amber-500 px-1.5 py-0.5 text-[11px] font-black text-black">{badge}</span>}</a>;
 return <div className="fixed inset-0 z-[100]"><button type="button" aria-label="Close menu" onClick={onClose} className="app-overlay absolute inset-0 backdrop-blur-[2px]"/><aside role="dialog" aria-modal="true" aria-label="Navigation menu" className="app-surface absolute right-0 top-0 flex h-full w-[min(90vw,390px)] flex-col overflow-y-auto border-l border-border shadow-2xl">
  <div className="flex items-center justify-between border-b border-border px-5 py-5"><BrandLogo/><button type="button" onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl border border-border text-muted-foreground"><X size={20}/></button></div>
  <div className="border-b border-border px-5 py-5"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-muted-foreground">{t.navigation.seller}</p><p className="mt-2 truncate font-semibold">{sellerName||"MTG Display CR"}</p>{sellerSlug?<p className="mt-1 truncate text-sm text-muted-foreground">@{sellerSlug}</p>:<p className="mt-1 text-sm text-muted-foreground">{t.navigation.storeNotConfigured}</p>}</div>
  <nav className="border-b border-border p-3">{row(t.navigation.dashboard,"/dashboard",LayoutDashboard)}{row(language==="es"?"Mi carrito":"My cart","/cart",ShoppingCart)}{row(language==="es"?"Mis pedidos":"My orders","/orders",ShoppingBag,pendingBuyerActions)}</nav>
  <nav className="border-b border-border p-3"><p className="px-4 pb-2 pt-1 text-[10px] font-bold uppercase tracking-[.18em] text-muted-foreground">{language==="es"?"VENDEDOR":"SELLER"}</p>{row(t.navigation.catalog,"/catalog",Package)}{row(language==="es"?"Ventas pendientes":"Pending Sales","/pending-sales",Clock3,pendingSellerActions)}{row(t.navigation.importCards,"/import",Upload)}{row(t.navigation.pricingSettings,"/settings/pricing",DollarSign)}{publicPath&&<button type="button" onClick={()=>void copyStoreLink()} className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold text-muted-foreground transition hover:bg-secondary hover:text-foreground"><Copy size={18}/>{t.navigation.copyStoreLink}</button>}</nav>
  <div className="border-b border-border px-5 py-5"><p className="mb-4 text-[10px] font-bold uppercase tracking-[.18em] text-muted-foreground">{t.navigation.preferences}</p><div className="space-y-5"><div><p className="mb-2 text-xs text-muted-foreground">{t.navigation.language}</p><LanguageSwitch/></div><div><p className="mb-2 text-xs text-muted-foreground">{t.navigation.theme}</p><ThemeSwitch/></div></div></div>
  <div className="mt-auto border-t border-border p-3">{row(language==="es"?"Mi perfil":"My Profile","/profile",UserRound)}<button type="button" onClick={()=>void signOut()} className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold text-red-400 transition hover:bg-red-500/10"><LogOut size={18}/>{t.navigation.signOut}</button></div>
 </aside></div>;
}