"use client";

import { useEffect, useRef, useState } from "react";
import { Eye, EyeOff, LockKeyhole, MoreHorizontal, Pencil, Plus, Trash2, X } from "lucide-react";
import { getSupabase } from "@/lib/supabase";
import { DEFAULT_LANGUAGE, LANGUAGE_STORAGE_KEY, type Language } from "@/lib/i18n";

type Binder={id:number;name:string;is_default:boolean;is_public:boolean};
type BinderStats=Binder&{listings:number;cards:number};

type Props={sellerId:string;onOpen:(binder:Binder)=>void};

export default function CatalogBinderHome({sellerId,onOpen}:Props){
 const supabase=getSupabase();
 const[binders,setBinders]=useState<BinderStats[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[menu,setMenu]=useState<number|null>(null),[createOpen,setCreateOpen]=useState(false),[newName,setNewName]=useState(""),[rename,setRename]=useState<BinderStats|null>(null),[renameName,setRenameName]=useState(""),[deleting,setDeleting]=useState<BinderStats|null>(null),[working,setWorking]=useState(false),[language,setLanguage]=useState<Language>(DEFAULT_LANGUAGE);const es=language==="es";const menuRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{const stored=localStorage.getItem(LANGUAGE_STORAGE_KEY);if(stored==="es"||stored==="en")setLanguage(stored);const h=(e:Event)=>{const v=(e as CustomEvent<Language>).detail;if(v==="es"||v==="en")setLanguage(v)};window.addEventListener("mtg-language-change",h);return()=>window.removeEventListener("mtg-language-change",h)},[]);
 useEffect(()=>{function close(e:MouseEvent){if(menuRef.current&&!menuRef.current.contains(e.target as Node))setMenu(null)}document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
 async function load(){if(!supabase)return;setLoading(true);const[b,i]=await Promise.all([supabase.from("binders").select("id,name,is_default,is_public").eq("seller_id",sellerId).order("is_default",{ascending:false}).order("name"),supabase.from("inventory_items").select("binder_id,quantity").eq("seller_id",sellerId).gt("quantity",0)]);if(b.error||i.error){setNotice(b.error?.message||i.error?.message||"");setLoading(false);return}const rows=(b.data||[]) as Binder[];const inventory=(i.data||[]) as {binder_id:number|null;quantity:number}[];setBinders(rows.map(x=>{const owned=inventory.filter(v=>v.binder_id===x.id);return{...x,listings:owned.length,cards:owned.reduce((s,v)=>s+Number(v.quantity||0),0)}}));setLoading(false)}
 useEffect(()=>{void load()},[sellerId,supabase]);
 async function createBinder(){if(!supabase||!newName.trim())return;setWorking(true);const{error}=await supabase.from("binders").insert({seller_id:sellerId,name:newName.trim(),is_default:false,is_public:true});setWorking(false);if(error){setNotice(error.message);return}setNewName("");setCreateOpen(false);await load()}
 async function renameBinder(){if(!supabase||!rename||!renameName.trim())return;setWorking(true);const{error}=await supabase.from("binders").update({name:renameName.trim(),updated_at:new Date().toISOString()}).eq("id",rename.id).eq("seller_id",sellerId);setWorking(false);if(error){setNotice(error.message);return}setRename(null);await load()}
 async function togglePublic(b:BinderStats){if(!supabase)return;setMenu(null);const{error}=await supabase.from("binders").update({is_public:!b.is_public,updated_at:new Date().toISOString()}).eq("id",b.id).eq("seller_id",sellerId);if(error){setNotice(error.message);return}await load()}
 async function deleteBinder(){if(!supabase||!deleting)return;setWorking(true);const{error}=await supabase.rpc("delete_binder",{p_binder_id:deleting.id});setWorking(false);if(error){setNotice(error.message);return}setDeleting(null);await load()}
 if(loading)return <section className="mt-8 rounded-3xl border border-border bg-card p-8 text-center text-muted-foreground">{es?"Cargando binders…":"Loading binders…"}</section>;
 return <>
  {notice&&<div className="mt-5 rounded-2xl border border-border bg-card px-4 py-3 text-sm text-muted-foreground">{notice}</div>}
  <div className="mt-7 flex justify-end"><button onClick={()=>setCreateOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground"><Plus size={18}/>{es?"Crear Binder":"Create Binder"}</button></div>
  <section className="mt-4 overflow-visible rounded-3xl border border-border bg-card">
   <div className="hidden grid-cols-[1fr_130px_130px_90px] gap-3 border-b border-border px-6 py-4 text-xs font-bold uppercase tracking-wider text-muted-foreground md:grid"><span>Binder</span><span>{es?"Listados":"Listings"}</span><span>{es?"Cartas":"Cards"}</span><span className="text-center">{es?"Acciones":"Actions"}</span></div>
   {binders.map(b=><div key={b.id} className="grid gap-3 border-b border-border px-5 py-5 last:border-b-0 md:grid-cols-[1fr_130px_130px_90px] md:items-center md:px-6">
    <button onClick={()=>onOpen(b)} className="flex items-center gap-2 text-left font-bold hover:text-primary"><span className="underline decoration-primary/30 underline-offset-4">{b.name}</span>{b.is_default&&<LockKeyhole size={15} className="text-primary"/>}{!b.is_public&&<EyeOff size={15} className="text-muted-foreground"/>}</button>
    <div><span className="mr-2 text-xs text-muted-foreground md:hidden">{es?"Listados":"Listings"}</span><strong>{b.listings}</strong></div><div><span className="mr-2 text-xs text-muted-foreground md:hidden">{es?"Cartas":"Cards"}</span><strong>{b.cards}</strong></div>
    <div className="relative flex justify-start md:justify-center" ref={menu===b.id?menuRef:undefined}><button onClick={()=>setMenu(menu===b.id?null:b.id)} aria-label={es?"Opciones del binder":"Binder options"} className="grid h-9 w-9 place-items-center rounded-lg border border-border bg-background text-muted-foreground hover:text-foreground"><MoreHorizontal size={19}/></button>{menu===b.id&&<div className="absolute right-0 top-11 z-30 w-56 rounded-xl border border-border bg-background p-1.5 shadow-2xl">
     {!b.is_default&&<button onClick={()=>{setRename(b);setRenameName(b.name);setMenu(null)}} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-secondary"><Pencil size={16}/>{es?"Renombrar Binder":"Rename Binder"}</button>}
     <button onClick={()=>void togglePublic(b)} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-secondary">{b.is_public?<EyeOff size={16}/>:<Eye size={16}/>} {b.is_public?(es?"Hacer privado":"Make private"):(es?"Hacer público":"Make public")}</button>
     {!b.is_default&&<><div className="my-1 border-t border-border"/><button onClick={()=>{setDeleting(b);setMenu(null)}} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm text-red-500 hover:bg-red-500/10"><Trash2 size={16}/>{es?"Eliminar Binder":"Delete Binder"}</button></>}
    </div>}</div>
   </div>)}
  </section>
  {binders.length===0&&<p className="mt-6 text-center text-muted-foreground">{es?"No tienes binders todavía.":"You do not have any binders yet."}</p>}
  {(createOpen||rename||deleting)&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/70 p-5"><div className="w-full max-w-md rounded-3xl border border-border bg-card p-6 shadow-2xl">
   <div className="flex items-start justify-between gap-4"><h2 className="font-serif text-2xl">{deleting?(es?"Eliminar Binder":"Delete Binder"):rename?(es?"Renombrar Binder":"Rename Binder"):(es?"Crear Binder":"Create Binder")}</h2><button onClick={()=>{setCreateOpen(false);setRename(null);setDeleting(null)}} className="text-muted-foreground"><X/></button></div>
   {deleting?<><p className="mt-5 text-sm leading-6 text-muted-foreground">{es?<>¿Seguro que deseas eliminar el Binder <strong className="text-foreground">{deleting.name}</strong>? Las cartas que se encuentren dentro de este Binder se trasladarán al <strong className="text-foreground">Trade Binder</strong> y no se podrá restaurar el Binder.</>:<>Are you sure you want to delete <strong className="text-foreground">{deleting.name}</strong>? Cards in this Binder will be moved to <strong className="text-foreground">Trade Binder</strong> and the Binder cannot be restored.</>}</p><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setDeleting(null)} className="rounded-xl border border-border px-4 py-2.5 font-semibold">{es?"Cancelar":"Cancel"}</button><button disabled={working} onClick={()=>void deleteBinder()} className="rounded-xl bg-red-600 px-4 py-2.5 font-bold text-white disabled:opacity-50">{es?"Eliminar Binder":"Delete Binder"}</button></div></>:<><label className="mt-5 block text-sm font-semibold">{es?"Nombre del Binder":"Binder name"}</label><input autoFocus value={rename?renameName:newName} onChange={e=>rename?setRenameName(e.target.value):setNewName(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void(rename?renameBinder():createBinder())}} maxLength={80} className="mt-2 h-11 w-full rounded-xl border border-border bg-background px-3 outline-none focus:border-primary" placeholder={es?"Ej. Goodies":"e.g. Goodies"}/><p className="mt-2 text-xs text-muted-foreground">{es?"Los nuevos Binders son públicos por defecto. Puedes cambiar su visibilidad desde ⚙.":"New Binders are public by default. You can change visibility from ⚙."}</p><div className="mt-6 flex justify-end gap-3"><button onClick={()=>{setCreateOpen(false);setRename(null)}} className="rounded-xl border border-border px-4 py-2.5 font-semibold">{es?"Cancelar":"Cancel"}</button><button disabled={working||!(rename?renameName:newName).trim()} onClick={()=>void(rename?renameBinder():createBinder())} className="rounded-xl bg-primary px-4 py-2.5 font-bold text-primary-foreground disabled:opacity-50">{rename?(es?"Guardar nombre":"Save name"):(es?"Crear Binder":"Create Binder")}</button></div></>}
  </div></div>}
 </>
}
