"use client";

import { useEffect, useMemo, useState } from "react";
import InventoryEditModal from "@/components/InventoryEditModal";
import { getSupabase } from "@/lib/supabase";
import { DEFAULT_LANGUAGE, LANGUAGE_STORAGE_KEY, type Language } from "@/lib/i18n";

type Binder={id:number;name:string;is_default:boolean;is_public:boolean};
type Item={id:number;quantity:number;condition:string;language:string;finish:string;pricing_mode:"default"|"custom"|"discount";custom_price_crc:number|null;binder_id:number|null;cards:{name:string;set_code:string;collector_number:string;image_uri:string|null}|null};

export default function CatalogInventoryEditor(){
 const supabase=getSupabase();
 const[items,setItems]=useState<Item[]>([]),[binders,setBinders]=useState<Binder[]>([]),[index,setIndex]=useState(-1),[notice,setNotice]=useState("");
 const[language,setLanguage]=useState<Language>(DEFAULT_LANGUAGE);const es=language==="es";
 const selectedBinderId=useMemo(()=>{if(typeof window==="undefined")return null;const match=window.location.pathname.match(/^\/catalog\/(?:singles\/binders|binders)\/(\d+)\/?$/);if(!match)return null;const id=Number(match[1]);return Number.isFinite(id)?id:null},[]);
 useEffect(()=>{const stored=localStorage.getItem(LANGUAGE_STORAGE_KEY);if(stored==="es"||stored==="en")setLanguage(stored);const h=(e:Event)=>{const v=(e as CustomEvent<Language>).detail;if(v==="es"||v==="en")setLanguage(v)};window.addEventListener("mtg-language-change",h);return()=>window.removeEventListener("mtg-language-change",h)},[]);
 async function load(){if(!supabase||selectedBinderId==null){setItems([]);return}setNotice("");const{data:auth}=await supabase.auth.getUser();const user=auth.user;if(!user)return;const[itemResult,binderResult]=await Promise.all([supabase.from("inventory_items").select("id,quantity,condition,language,finish,pricing_mode,custom_price_crc,binder_id,cards(name,set_code,collector_number,image_uri)").eq("seller_id",user.id).eq("binder_id",selectedBinderId).gt("quantity",0).order("updated_at",{ascending:false}),supabase.from("binders").select("id,name,is_default,is_public").eq("seller_id",user.id).order("is_default",{ascending:false}).order("name")]);if(itemResult.error)setNotice(itemResult.error.message);else setItems((itemResult.data||[]) as unknown as Item[]);if(binderResult.error)setNotice(binderResult.error.message);else setBinders((binderResult.data||[]) as Binder[])}
 useEffect(()=>{void load()},[supabase,selectedBinderId]);
 useEffect(()=>{if(selectedBinderId==null)return;function getIndex(target:EventTarget|null){const el=target instanceof Element?target:null;if(!el)return-1;const heading=el.closest("[data-inventory-item-id]");if(!(heading instanceof HTMLElement))return-1;const id=Number(heading.dataset.inventoryItemId);return items.findIndex(item=>item.id===id)}function onClick(e:MouseEvent){const i=getIndex(e.target);if(i<0)return;e.preventDefault();e.stopPropagation();setIndex(i)}function onKey(e:KeyboardEvent){if(e.key!=="Enter"&&e.key!==" ")return;const i=getIndex(e.target);if(i<0)return;e.preventDefault();e.stopPropagation();setIndex(i)}function decorate(){document.querySelectorAll<HTMLElement>("[data-inventory-item-id]").forEach(node=>{node.style.cursor="pointer";node.style.textDecoration="underline";node.style.textDecorationColor="rgba(163,230,53,.45)";node.style.textUnderlineOffset="3px";node.setAttribute("role","button");node.setAttribute("tabindex","0");node.setAttribute("title",es?"Editar esta carta":"Edit this card")})}decorate();const observer=new MutationObserver(decorate);observer.observe(document.body,{childList:true,subtree:true});document.addEventListener("click",onClick);document.addEventListener("keydown",onKey);return()=>{observer.disconnect();document.removeEventListener("click",onClick);document.removeEventListener("keydown",onKey)}},[items,es,selectedBinderId]);
 const item=useMemo(()=>index>=0?items[index]??null:null,[items,index]);
 async function save(next:Item){if(!supabase)return;const payload={quantity:next.quantity,condition:next.condition,language:next.language,finish:next.finish,pricing_mode:next.pricing_mode,custom_price_crc:next.pricing_mode==="custom"?next.custom_price_crc:null,binder_id:next.binder_id,available:next.quantity>0,updated_at:new Date().toISOString()};const{error}=await supabase.from("inventory_items").update(payload).eq("id",next.id);if(error){setNotice(error.message);return}setNotice(es?"Cambios guardados.":"Changes saved.");setIndex(-1);window.location.reload()}
 async function createBinder(name:string):Promise<Binder|null>{if(!supabase)return null;const{data:auth}=await supabase.auth.getUser();if(!auth.user)return null;const clean=name.trim();if(!clean)return null;const{data,error}=await supabase.from("binders").insert({seller_id:auth.user.id,name:clean,is_default:false,is_public:true}).select("id,name,is_default,is_public").single();if(error){setNotice(error.message);return null}const created=data as Binder;setBinders(current=>[...current,created].sort((a,b)=>Number(b.is_default)-Number(a.is_default)||a.name.localeCompare(b.name)));return created}
 if(selectedBinderId==null)return null;
 return <>{notice&&<div className="fixed bottom-4 left-1/2 z-[100] -translate-x-1/2 rounded-xl border border-border bg-card px-4 py-3 text-sm shadow-2xl">{notice}</div>}<InventoryEditModal open={index>=0} item={item} binders={binders} language={language} hasPrevious={index>0} hasNext={index>=0&&index<items.length-1} onClose={()=>setIndex(-1)} onPrevious={()=>setIndex(i=>Math.max(0,i-1))} onNext={()=>setIndex(i=>Math.min(items.length-1,i+1))} onSave={save} onCreateBinder={createBinder}/></>
}
