"use client";

import { useEffect, useLayoutEffect, useRef, useState } from "react";
import { ArrowLeft } from "lucide-react";
import CatalogBinderHome from "@/components/CatalogBinderHome";
import { getSupabase } from "@/lib/supabase";
import { DEFAULT_LANGUAGE, LANGUAGE_STORAGE_KEY, type Language } from "@/lib/i18n";

type Binder={id:number;name:string;is_default:boolean;is_public:boolean};
type AllowedCard={name:string;set:string;collector:string;pricing_mode:string};

export default function CatalogBinderNavigation(){
 const supabase=getSupabase();
 const[userId,setUserId]=useState<string|null>(null),[binder,setBinder]=useState<Binder|null>(null),[ready,setReady]=useState(false),[scoped,setScoped]=useState(false),[language,setLanguage]=useState<Language>(DEFAULT_LANGUAGE),[allowed,setAllowed]=useState<AllowedCard[]>([]);const es=language==="es";
 const applying=useRef(false),frameRef=useRef(0);
 const binderId=typeof window!=="undefined"?Number(new URLSearchParams(window.location.search).get("binder"))||null:null;
 useEffect(()=>{const sync=()=>{const stored=localStorage.getItem(LANGUAGE_STORAGE_KEY);if(stored==="es"||stored==="en")setLanguage(stored)};sync();const h=(e:Event)=>{const v=(e as CustomEvent<Language>).detail;if(v==="es"||v==="en")setLanguage(v);else sync()};window.addEventListener("mtg-language-change",h);window.addEventListener("storage",sync);return()=>{window.removeEventListener("mtg-language-change",h);window.removeEventListener("storage",sync)}},[]);
 useEffect(()=>{let cancelled=false;if(!supabase){setReady(true);return}setReady(false);setScoped(false);setBinder(null);setAllowed([]);supabase.auth.getUser().then(async({data})=>{if(cancelled)return;const id=data.user?.id||null;setUserId(id);if(id&&binderId){const[binderResult,inventoryResult]=await Promise.all([supabase.from("binders").select("id,name,is_default,is_public").eq("id",binderId).eq("seller_id",id).maybeSingle(),supabase.from("inventory_items").select("pricing_mode,cards(name,set_code,collector_number)").eq("seller_id",id).eq("binder_id",binderId).gt("quantity",0)]);if(cancelled)return;setBinder((binderResult.data as Binder|null)||null);setAllowed((inventoryResult.data||[]).map((x:any)=>({name:x.cards?.name||"",set:(x.cards?.set_code||"").toUpperCase(),collector:String(x.cards?.collector_number||""),pricing_mode:x.pricing_mode||"default"})))}if(!cancelled)setReady(true)});return()=>{cancelled=true}},[supabase,binderId]);
 useLayoutEffect(()=>{if(!ready||!binderId||!binder)return;function matches(article:Element){const heading=article.querySelector("h2")?.textContent?.trim()||"";const detail=Array.from(article.querySelectorAll("p")).map(p=>p.textContent||"").join(" ");return allowed.some(a=>a.name===heading&&(!a.set||detail.includes(a.set))&&(!a.collector||detail.includes(`#${a.collector}`)))}function apply(initial=false){if(applying.current)return;applying.current=true;try{const root=document.querySelector("main");if(!root)return;const h1=root.querySelector("h1") as HTMLElement|null;if(h1)h1.textContent=`${es?"Tu catálogo":"Your Catalog"} [ ${binder.name} ]`;root.querySelectorAll("article").forEach(article=>{(article as HTMLElement).style.display=matches(article)?"":"none"});const count={all:allowed.length,default:allowed.filter(a=>a.pricing_mode==="default").length,custom:allowed.filter(a=>a.pricing_mode==="custom").length,discount:allowed.filter(a=>a.pricing_mode==="discount").length};const labels=es?["Todos","Predeterminado","Personalizado","Descuento"]:["All","Default","Custom","Discount"];const values=[count.all,count.default,count.custom,count.discount];const filterSection=Array.from(root.querySelectorAll("section")).find(s=>labels.some(l=>(s.textContent||"").includes(`${l} (`)));if(filterSection){const buttons=Array.from(filterSection.querySelectorAll("button"));labels.forEach((label,i)=>{const button=buttons.find(b=>(b.textContent||"").trim().startsWith(`${label} (`));if(button)button.textContent=`${label} (${values[i]})`});const shown=Array.from(filterSection.querySelectorAll("span")).find(s=>/\d+\s+(shown|mostradas|mostrados)/i.test((s.textContent||"").trim()));if(shown)shown.textContent=`${count.all} ${es?"mostradas":"shown"}`};const subtitle=h1?.nextElementSibling as HTMLElement|null;if(subtitle&&/\d+/.test(subtitle.textContent||""))subtitle.textContent=`${count.all} ${es?"listados en este Binder":"listings in this Binder"}`;if(initial)setScoped(true)}finally{applying.current=false}}
 apply(true);function schedule(){cancelAnimationFrame(frameRef.current);frameRef.current=requestAnimationFrame(()=>apply(false))}const observer=new MutationObserver(schedule);observer.observe(document.querySelector("main")||document.body,{childList:true,subtree:true,characterData:true});return()=>{cancelAnimationFrame(frameRef.current);observer.disconnect();document.querySelectorAll("article").forEach(a=>(a as HTMLElement).style.display="")}},[ready,binderId,binder,allowed,es]);
 const loadingLabel=binderId?(es?"Cargando Binder…":"Loading Binder…"):(es?"Cargando Binders…":"Loading Binders…");
 if(!ready||!userId)return <div className="fixed inset-0 z-[90] grid place-items-center bg-background text-muted-foreground"><div className="flex flex-col items-center gap-3"><div className="h-7 w-7 animate-spin rounded-full border-2 border-border border-t-primary"/><span className="text-sm">{loadingLabel}</span></div></div>;
 if(!binderId)return <div className="fixed inset-x-0 bottom-0 top-16 z-40 overflow-y-auto bg-background text-foreground"><div className="mx-auto max-w-7xl px-5 py-8"><p className="text-xs font-bold uppercase tracking-[.15em] text-primary">{es?"INVENTARIO DEL VENDEDOR":"SELLER INVENTORY"}</p><h1 className="mt-2 font-serif text-4xl">{es?"Tu catálogo":"Your Catalog"}</h1><p className="mt-2 text-muted-foreground">{es?"Organiza tu inventario por Binders.":"Organize your inventory by Binders."}</p><CatalogBinderHome sellerId={userId} onOpen={b=>{window.location.href=`/catalog?binder=${b.id}`}}/></div></div>;
 if(!binder)return <div className="fixed inset-x-0 top-16 z-40 border-b border-border bg-background px-5 py-3 text-center text-sm text-red-500">{es?"Binder no encontrado.":"Binder not found."}</div>;
 return <>{!scoped&&<div className="fixed inset-0 z-[90] grid place-items-center bg-background text-muted-foreground"><div className="flex flex-col items-center gap-3"><div className="h-7 w-7 animate-spin rounded-full border-2 border-border border-t-primary"/><span className="text-sm">{es?"Preparando Binder…":"Preparing Binder…"}</span></div></div>}<a href="/catalog" className="fixed left-5 top-[76px] z-[35] inline-flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-2 text-sm font-semibold shadow-lg hover:text-primary"><ArrowLeft size={16}/>{es?"Todos los Binders":"All Binders"}</a><style jsx global>{`main section.sticky{top:76px!important;z-index:45!important}main section.sticky>div{min-width:0}main section.sticky .flex.flex-wrap{align-items:center}@media(max-width:900px){main section.sticky{left:8px;right:8px}main section.sticky button{white-space:nowrap}}`}</style></>;
}
