"use client";

import {useEffect,useState} from "react";
import {ArrowLeft,ArrowRight,LayoutDashboard,PackageCheck,Search,ShoppingBag,Store} from "lucide-react";

type Props={es:boolean;signedIn:boolean};

export default function HomeHeroCarousel({es,signedIn}:Props){
 const[index,setIndex]=useState(0);
 useEffect(()=>{const timer=window.setInterval(()=>setIndex(i=>(i+1)%3),8000);return()=>window.clearInterval(timer)},[]);
 const slides=[
  <div key="marketplace" className="flex h-full flex-col justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-primary">{es?"Marketplace de Magic en Costa Rica":"Magic marketplace in Costa Rica"}</p><h1 className="mt-4 max-w-3xl font-serif text-4xl font-bold leading-[.98] tracking-tight sm:text-5xl lg:text-6xl">{es?"Compra y vende Magic":"Buy and sell Magic"}<span className="block text-primary">{es?"en Costa Rica.":"in Costa Rica."}</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-muted-foreground sm:text-base">{es?"Encuentra cartas de vendedores locales y administra tu vitrina desde un solo lugar.":"Find cards from local sellers and manage your display from one place."}</p></div><div className="mt-6 flex flex-wrap gap-3"><a href="#cards" className="inline-flex h-11 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-primary-foreground">{es?"Explorar cartas":"Explore cards"}<ArrowRight size={16}/></a><a href={signedIn?"/dashboard":"/profile"} className="inline-flex h-11 items-center gap-2 rounded-xl border border-border bg-card px-5 text-sm font-bold"><LayoutDashboard size={16}/>{signedIn?(es?"Ir al Dashboard":"Go to Dashboard"):(es?"Vender mis cartas":"Sell my cards")}</a></div></div>,
  <div key="display" className="flex h-full flex-col justify-center"><p className="text-xs font-black uppercase tracking-[.16em] text-muted-foreground">MTG DISPLAY CR</p><h2 className="mt-4 max-w-2xl font-serif text-4xl font-bold leading-tight sm:text-5xl">{es?"Tu colección puede ser tu vitrina.":"Your collection can be your display."}</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-muted-foreground sm:text-base">{es?"Publica Binders, define tus precios y recibe pedidos sin perder el control de tu inventario.":"Publish Binders, set your prices, and receive orders without losing control of your inventory."}</p><div className="mt-6 grid max-w-2xl gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-border bg-background/60 p-4"><ShoppingBag className="text-primary" size={20}/><strong className="mt-3 block text-sm">{es?"Compra local":"Buy local"}</strong><p className="mt-1 text-xs leading-5 text-muted-foreground">{es?"Precios en colones y vendedores de Costa Rica.":"Prices in colones from Costa Rican sellers."}</p></div><div className="rounded-2xl border border-border bg-background/60 p-4"><Store className="text-primary" size={20}/><strong className="mt-3 block text-sm">{es?"Vende fácil":"Sell simply"}</strong><p className="mt-1 text-xs leading-5 text-muted-foreground">{es?"Importa, organiza y publica tu inventario.":"Import, organize, and publish your inventory."}</p></div></div></div>,
  <div key="how" className="flex h-full flex-col justify-center"><p className="text-xs font-black uppercase tracking-[.16em] text-primary">{es?"Simple":"Simple"}</p><h2 className="mt-3 font-serif text-4xl font-bold sm:text-5xl">{es?"Cómo funciona":"How it works"}</h2><div className="mt-6 grid gap-3 md:grid-cols-3">{[[Search,es?"Explora":"Explore",es?"Encuentra cartas entre las vitrinas disponibles.":"Find cards across available displays."],[ShoppingBag,es?"Compra":"Buy",es?"Crea tu pedido y sigue su estado.":"Place your order and track its status."],[PackageCheck,es?"Coordina":"Coordinate",es?"Confirma pago, entrega y recepción.":"Confirm payment, delivery, and receipt."]].map(([Icon,title,text],n)=>{const I=Icon as typeof Search;return <div key={String(title)} className="rounded-2xl border border-border bg-background/60 p-4"><I className="text-primary" size={20}/><span className="mt-3 block text-[10px] font-black text-muted-foreground">0{n+1}</span><strong className="mt-1 block text-sm">{String(title)}</strong><p className="mt-1 text-xs leading-5 text-muted-foreground">{String(text)}</p></div>})}</div></div>
 ];
 return <section className="border-b border-border"><div className="mx-auto max-w-7xl px-5 py-5 sm:px-7 sm:py-7"><div className="relative min-h-[330px] overflow-hidden rounded-3xl border border-border bg-card p-6 sm:min-h-[350px] sm:p-8 lg:p-10"><div className="h-full pr-0 sm:pr-16">{slides[index]}</div><div className="mt-7 flex items-center justify-between gap-4 sm:absolute sm:bottom-7 sm:right-8 sm:mt-0"><div className="flex gap-2">{slides.map((_,i)=><button key={i} type="button" onClick={()=>setIndex(i)} aria-label={`${es?"Ir al slide":"Go to slide"} ${i+1}`} className={`h-2.5 rounded-full transition-all ${i===index?"w-7 bg-primary":"w-2.5 bg-muted-foreground/40"}`}/>)}</div><div className="flex gap-2"><button type="button" onClick={()=>setIndex(i=>(i+2)%3)} aria-label={es?"Anterior":"Previous"} className="grid h-9 w-9 place-items-center rounded-xl border border-border bg-background/70 text-muted-foreground hover:text-foreground"><ArrowLeft size={16}/></button><button type="button" onClick={()=>setIndex(i=>(i+1)%3)} aria-label={es?"Siguiente":"Next"} className="grid h-9 w-9 place-items-center rounded-xl border border-border bg-background/70 text-muted-foreground hover:text-foreground"><ArrowRight size={16}/></button></div></div></div></div></section>
}
