"use client";

import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Plus, X } from "lucide-react";

type Binder={id:number;name:string;is_default:boolean;is_public:boolean};
type Item={id:number;quantity:number;condition:string;language:string;finish:string;pricing_mode:"default"|"custom"|"discount";custom_price_crc:number|null;binder_id:number|null;cards:{name:string;set_code:string;collector_number:string;image_uri:string|null}|null};
type Props={open:boolean;item:Item|null;binders:Binder[];language:"es"|"en";hasPrevious:boolean;hasNext:boolean;onClose:()=>void;onPrevious:()=>void;onNext:()=>void;onSave:(item:Item)=>Promise<void>;onCreateBinder:(name:string)=>Promise<Binder|null>};

export default function InventoryEditModal(p:Props){
 const[form,setForm]=useState<Item|null>(p.item),[saving,setSaving]=useState(false),[creating,setCreating]=useState(false),[binderName,setBinderName]=useState("");const es=p.language==="es";
 useEffect(()=>setForm(p.item),[p.item]);if(!p.open||!form)return null;
 const field="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary";
 async function save(){setSaving(true);try{await p.onSave(form)}finally{setSaving(false)}}
 async function createBinder(){const name=binderName.trim();if(!name)return;const b=await p.onCreateBinder(name);if(b){setForm({...form,binder_id:b.id});setBinderName("");setCreating(false)}}
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-3" onMouseDown={e=>{if(e.target===e.currentTarget)p.onClose()}}><section className="max-h-[94vh] w-full max-w-5xl overflow-y-auto rounded-3xl border border-border bg-card shadow-2xl">
  <header className="flex items-center justify-between border-b border-border px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-primary">{es?"Inventario":"Inventory"}</p><h2 className="font-serif text-2xl">{es?"Editar carta":"Edit card"}</h2></div><button onClick={p.onClose} className="rounded-xl border border-border p-2 text-muted-foreground hover:text-foreground"><X size={20}/></button></header>
  <div className="grid gap-6 p-5 md:grid-cols-[260px_1fr]">
   <div>{form.cards?.image_uri?<img src={form.cards.image_uri} alt={form.cards.name} className="w-full rounded-2xl"/>:<div className="aspect-[5/7] rounded-2xl bg-secondary"/>}<div className="mt-3 text-center"><strong>{form.cards?.name||"Card"}</strong><p className="text-sm text-muted-foreground">{form.cards?.set_code?.toUpperCase()} #{form.cards?.collector_number}</p></div></div>
   <div className="space-y-5">
    <div className="grid gap-4 sm:grid-cols-[140px_1fr]"><label className="text-sm">{es?"Cantidad":"Quantity"}<input type="number" min={0} value={form.quantity} onChange={e=>setForm({...form,quantity:Math.max(0,Number(e.target.value)||0)})} className={`${field} mt-2`}/></label><label className="text-sm">{es?"Carta / impresión":"Card / printing"}<div className={`${field} mt-2 flex items-center text-muted-foreground`}>{form.cards?.name} · {form.cards?.set_code?.toUpperCase()} #{form.cards?.collector_number}</div></label></div>
    <div className="grid gap-4 sm:grid-cols-3"><label className="text-sm">{es?"Condición":"Condition"}<select value={form.condition} onChange={e=>setForm({...form,condition:e.target.value})} className={`${field} mt-2`}>{["NM","LP","MP","HP","DMG"].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm">{es?"Idioma":"Language"}<select value={form.language} onChange={e=>setForm({...form,language:e.target.value})} className={`${field} mt-2`}><option value="en">English</option><option value="es">Español</option><option value="ja">日本語</option><option value="fr">Français</option><option value="de">Deutsch</option><option value="it">Italiano</option><option value="pt">Português</option></select></label><label className="text-sm">Finish<select value={form.finish} onChange={e=>setForm({...form,finish:e.target.value})} className={`${field} mt-2`}><option value="nonfoil">Nonfoil</option><option value="foil">Foil</option><option value="etched">Etched</option></select></label></div>
    <div><span className="text-sm">{es?"Precio de venta":"Sale price"}</span><div className="mt-2 grid gap-2 sm:grid-cols-3">{([['default',es?'Predeterminado':'Default'],['custom',es?'Personalizado':'Custom'],['discount',es?'Descuento':'Discount']] as const).map(([v,l])=><button key={v} onClick={()=>setForm({...form,pricing_mode:v})} className={`rounded-xl border px-3 py-3 text-sm font-bold ${form.pricing_mode===v?'border-primary bg-primary/10 text-primary':'border-border'}`}>{l}</button>)}</div>{form.pricing_mode==='custom'&&<input type="number" min={0} value={form.custom_price_crc??0} onChange={e=>setForm({...form,custom_price_crc:Math.max(0,Number(e.target.value)||0)})} className={`${field} mt-3`} placeholder="CRC"/>}</div>
    <div className="rounded-2xl border border-primary/20 bg-primary/[.04] p-4"><div className="flex items-end gap-3"><label className="min-w-0 flex-1 text-sm">Binder<select value={form.binder_id??""} onChange={e=>setForm({...form,binder_id:Number(e.target.value)})} className={`${field} mt-2`}>{p.binders.map(b=><option key={b.id} value={b.id}>{b.name}{b.is_default?' 🔒':''}</option>)}</select></label><button onClick={()=>setCreating(!creating)} className="h-11 rounded-xl border border-border px-3"><Plus size={18}/></button></div>{creating&&<div className="mt-3 flex gap-2"><input value={binderName} maxLength={80} onChange={e=>setBinderName(e.target.value)} placeholder={es?'Nombre del binder':'Binder name'} className={field}/><button onClick={createBinder} className="rounded-xl bg-primary px-4 font-bold text-primary-foreground">{es?'Crear':'Create'}</button></div>}<p className="mt-2 text-xs text-muted-foreground">{es?'Trade Binder es el binder predeterminado y no puede renombrarse ni eliminarse.':'Trade Binder is the default binder and cannot be renamed or deleted.'}</p></div>
   </div>
  </div>
  <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-border p-5"><div className="flex gap-2"><button disabled={!p.hasPrevious} onClick={p.onPrevious} className="inline-flex h-11 items-center gap-1 rounded-xl border border-border px-4 disabled:opacity-30"><ChevronLeft size={17}/>{es?'Anterior':'Previous'}</button><button disabled={!p.hasNext} onClick={p.onNext} className="inline-flex h-11 items-center gap-1 rounded-xl border border-border px-4 disabled:opacity-30">{es?'Siguiente':'Next'}<ChevronRight size={17}/></button></div><div className="flex gap-2"><button onClick={p.onClose} className="h-11 rounded-xl border border-border px-5">{es?'Cancelar':'Cancel'}</button><button disabled={saving} onClick={save} className="h-11 rounded-xl bg-primary px-6 font-bold text-primary-foreground disabled:opacity-50">{saving?(es?'Guardando…':'Saving…'):(es?'Guardar cambios':'Save changes')}</button></div></footer>
 </section></div>
}
