"use client";

import {useEffect,useState} from "react";
import {ImagePlus,Trash2,Upload} from "lucide-react";
import {getSupabase} from "@/lib/supabase";

export const COVER_PRESETS=[
 {id:"portal",labelEs:"Portal",labelEn:"Portal",className:"bg-[radial-gradient(circle_at_50%_55%,#75dfff_0_8%,#225d72_9_22%,#152b2d_45%,#101612_75%)]"},
 {id:"forest",labelEs:"Bosque",labelEn:"Forest",className:"bg-[radial-gradient(circle_at_25%_35%,#6f9f39_0_8%,transparent_28%),linear-gradient(135deg,#172c1d,#294b2b_45%,#0d1711)]"},
 {id:"mountain",labelEs:"Montaña",labelEn:"Mountain",className:"bg-[linear-gradient(155deg,#4c2b21_0_25%,#a35a32_26%_38%,#34251e_39%_62%,#111713_63%)]"},
 {id:"ocean",labelEs:"Océano",labelEn:"Ocean",className:"bg-[radial-gradient(circle_at_70%_20%,#78d8e8_0_6%,transparent_22%),linear-gradient(160deg,#163c50,#176c7d_48%,#0c222a)]"},
 {id:"ember",labelEs:"Brasas",labelEn:"Ember",className:"bg-[radial-gradient(circle_at_65%_70%,#e87935_0_5%,#7b301d_20%,transparent_42%),linear-gradient(135deg,#291714,#111713)]"},
 {id:"arcane",labelEs:"Arcano",labelEn:"Arcane",className:"bg-[radial-gradient(circle_at_50%_45%,#a77cff_0_5%,#513b79_18%,transparent_38%),linear-gradient(145deg,#211934,#111713_70%)]"},
] as const;
export type CoverPreset=typeof COVER_PRESETS[number]["id"];
export function coverPresetClass(value?:string|null){return COVER_PRESETS.find(p=>p.id===value)?.className||COVER_PRESETS[0].className}

type Props={userId:string;es:boolean};
export default function ProfileCoverBannerEditor({userId,es}:Props){const[preset,setPreset]=useState<CoverPreset>("portal"),[path,setPath]=useState<string|null>(null),[store,setStore]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");const s=getSupabase();
 useEffect(()=>{if(!s)return;void s.from("profiles").select("seller_type,cover_banner_preset,cover_banner_path").eq("id",userId).single().then(({data})=>{setStore(data?.seller_type==="store");setPreset((data?.cover_banner_preset||"portal") as CoverPreset);setPath(data?.cover_banner_path||null)})},[s,userId]);
 const customUrl=path&&s?s.storage.from("store-banners").getPublicUrl(path).data.publicUrl:null;
 async function choose(next:CoverPreset){if(!s||busy)return;setBusy(true);setNotice("");const{error}=await s.from("profiles").update({cover_banner_preset:next,cover_banner_path:null,updated_at:new Date().toISOString()}).eq("id",userId);if(error)setNotice(error.message);else{if(path)await s.storage.from("store-banners").remove([path]);setPath(null);setPreset(next);setNotice(es?"Banner actualizado.":"Banner updated.")}setBusy(false)}
 async function upload(file:File){if(!s||!store)return;setNotice("");if(!["image/png","image/jpeg","image/webp"].includes(file.type)){setNotice(es?"Usa PNG, JPG o WebP.":"Use PNG, JPG or WebP.");return}if(file.size>5*1024*1024){setNotice(es?"El archivo debe pesar máximo 5 MB.":"File must be 5 MB or smaller.");return}const img=new Image(),object=URL.createObjectURL(file);img.onload=async()=>{URL.revokeObjectURL(object);if(img.width/img.height<2.4){setNotice(es?"El banner debe ser horizontal. Recomendado: 1200 × 360 px.":"Banner must be landscape. Recommended: 1200 × 360 px.");return}setBusy(true);const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg",next=`${userId}/cover.${ext}`;if(path&&path!==next)await s.storage.from("store-banners").remove([path]);const{error}=await s.storage.from("store-banners").upload(next,file,{upsert:true,contentType:file.type});if(error){setNotice(error.message);setBusy(false);return}const{error:db}=await s.from("profiles").update({cover_banner_path:next,updated_at:new Date().toISOString()}).eq("id",userId);if(db)setNotice(db.message);else{setPath(next);setNotice(es?"Banner personalizado actualizado.":"Custom banner updated.")}setBusy(false)};img.src=object}
 async function removeCustom(){if(!s||!path)return;setBusy(true);const old=path;const{error}=await s.from("profiles").update({cover_banner_path:null,updated_at:new Date().toISOString()}).eq("id",userId);if(!error){await s.storage.from("store-banners").remove([old]);setPath(null);setNotice(es?"Volviste al banner predeterminado.":"Preset banner restored.")}else setNotice(error.message);setBusy(false)}
 return <div className="mt-5 rounded-2xl border border-primary/30 bg-card p-5"><h3 className="font-bold">{es?"Banner de la vitrina":"Display cover banner"}</h3><p className="mt-1 text-sm text-muted-foreground">{es?"Elige uno de los diseños de MTG Display. Las tiendas también pueden subir un banner propio.":"Choose an MTG Display preset. Stores can also upload a custom banner."}</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{COVER_PRESETS.map(item=><button key={item.id} type="button" disabled={busy} onClick={()=>void choose(item.id)} className={`overflow-hidden rounded-xl border text-left ${!path&&preset===item.id?"border-primary":"border-border"}`}><div className={`h-16 ${item.className}`}/><div className="px-2 py-2 text-xs font-bold">{es?item.labelEs:item.labelEn}</div></button>)}</div>{store&&<div className="mt-5 border-t border-border pt-5"><div className={`h-28 overflow-hidden rounded-xl border border-border ${coverPresetClass(preset)}`}>{customUrl&&<img key={path} src={`${customUrl}?v=${encodeURIComponent(path||"")}`} alt="" className="h-full w-full object-cover"/>}</div><p className="mt-2 text-xs text-muted-foreground">{es?"Banner personalizado recomendado: 1200 × 360 px · PNG, JPG o WebP · máximo 5 MB. La imagen se recorta con cover para adaptarse.":"Recommended custom banner: 1200 × 360 px · PNG, JPG or WebP · maximum 5 MB. The image uses cover cropping to fit."}</p><div className="mt-3 flex flex-wrap gap-2"><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-primary-foreground"><Upload size={15}/>{path?(es?"Cambiar banner":"Change banner"):(es?"Subir banner":"Upload banner")}<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.currentTarget.value=""}}/></label>{path&&<button type="button" onClick={()=>void removeCustom()} disabled={busy} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm font-bold"><Trash2 size={15}/>{es?"Usar predeterminado":"Use preset"}</button>}</div></div>}{!store&&<div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><ImagePlus size={14}/>{es?"Los banners personalizados están disponibles para cuentas de tienda.":"Custom uploads are available for store accounts."}</div>}{notice&&<p className="mt-3 text-xs text-muted-foreground">{notice}</p>}</div>}
