"use client";
import{useEffect,useState}from"react";import{BellRing,BellOff,RefreshCw,Send}from"lucide-react";import{getSupabase}from"@/lib/supabase";type Props={userId:string};
function b64(s:string){const p="=".repeat((4-s.length%4)%4),raw=atob((s+p).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
function pushError(e:any){const raw=String(e?.message||e||"");if(Notification.permission==="denied")return"Las notificaciones están bloqueadas para este sitio. Habilítalas en la configuración del navegador y vuelve a intentarlo.";if(/no active Service Worker|activation timed out/i.test(raw))return"El Service Worker no logró activarse. Recarga la página y prueba Reparar notificaciones.";if(/Registration failed|Subscription failed|push service|AbortError/i.test(raw))return"El Service Worker está activo, pero el navegador no pudo registrarse con su servicio Push. Revisa conexión/VPN/firewall o prueba temporalmente otra red.";if(/InvalidAccess|applicationServerKey/i.test(raw))return"La clave Push pública no fue aceptada por este navegador.";return raw||"No se pudieron activar las notificaciones."}
function waitActive(r:ServiceWorkerRegistration,timeout=10000){if(r.active)return Promise.resolve(r);const worker=r.installing||r.waiting;if(!worker)return Promise.reject(new Error("No active Service Worker"));return new Promise<ServiceWorkerRegistration>((resolve,reject)=>{let done=false;const timer=setTimeout(()=>{if(done)return;done=true;reject(new Error("Service Worker activation timed out"))},timeout);const check=()=>{if(done)return;if(r.active||worker.state==="activated"){done=true;clearTimeout(timer);resolve(r)}else if(worker.state==="redundant"){done=true;clearTimeout(timer);reject(new Error("Service Worker became redundant"))}};worker.addEventListener("statechange",check);check()})}
export default function PushNotificationsSettings({userId}:Props){const s=getSupabase();const[supported,setSupported]=useState(true),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[showRepair,setShowRepair]=useState(false);
async function registration(){const regs=await navigator.serviceWorker.getRegistrations();for(const old of regs){if(old.scope===`${location.origin}/`&&old.active?.scriptURL&&!old.active.scriptURL.endsWith("/push-sw.js"))await old.unregister()}const r=await navigator.serviceWorker.register("/push-sw.js",{scope:"/",updateViaCache:"none"});await r.update().catch(()=>{});return waitActive(r)}
async function syncState(){try{const r=await registration(),sub=await r.pushManager.getSubscription();setEnabled(!!sub)}catch(e){setMessage(pushError(e))}}
useEffect(()=>{if(!("serviceWorker"in navigator)||!("PushManager"in window)||!("Notification"in window)){setSupported(false);return}void syncState()},[]);
async function save(sub:PushSubscription){if(!s)throw new Error("Supabase no está disponible");const j=sub.toJSON(),p256dh=j.keys?.p256dh,auth=j.keys?.auth;if(!p256dh||!auth)throw new Error("El navegador no devolvió las claves Push");const{error}=await s.from("push_subscriptions").upsert({user_id:userId,endpoint:sub.endpoint,p256dh,auth_key:auth,user_agent:navigator.userAgent,updated_at:new Date().toISOString()},{onConflict:"user_id,endpoint"});if(error)throw error}
async function subscribe(repair=false){const key=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(!key)throw new Error("VAPID public key is not configured");if(Notification.permission==="denied")throw new Error("Permission denied");if(await Notification.requestPermission()!=="granted")throw new Error("Permiso de notificaciones no concedido");const r=await registration();let sub=await r.pushManager.getSubscription();if(repair&&sub){await sub.unsubscribe().catch(()=>{});sub=null}if(!sub)sub=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(key)});await save(sub);setEnabled(true)}
async function enable(){setBusy(true);setMessage("");try{await subscribe(false);setShowRepair(false);setMessage("Notificaciones activadas en este dispositivo.")}catch(e){setShowRepair(true);setMessage(pushError(e))}finally{setBusy(false)}}
async function repair(){setBusy(true);setMessage("");try{const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs){const sub=await r.pushManager.getSubscription().catch(()=>null);if(sub)await sub.unsubscribe().catch(()=>{});await r.unregister().catch(()=>{})}await subscribe(true);setShowRepair(false);setMessage("Notificaciones reparadas y activadas en este dispositivo.")}catch(e){setEnabled(false);setShowRepair(true);setMessage(pushError(e))}finally{setBusy(false)}}
async function disable(){if(!s)return;setBusy(true);setMessage("");try{const r=await registration(),sub=await r.pushManager.getSubscription();if(sub){await s.from("push_subscriptions").delete().eq("user_id",userId).eq("endpoint",sub.endpoint);await sub.unsubscribe()}setEnabled(false);setShowRepair(false);setMessage("Notificaciones desactivadas en este dispositivo.")}catch(e){setMessage(pushError(e))}finally{setBusy(false)}}
async function testPush(){if(!s)return;setBusy(true);setMessage("");try{const{data:{session}}=await s.auth.getSession();if(!session?.access_token)throw new Error("Sesión no disponible");const res=await fetch("/api/push/test",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`}});const data=await res.json();if(!res.ok)throw new Error(data.error||data.errors?.[0]||"No se pudo enviar el Push");setMessage(`Push enviado a ${data.sent} dispositivo${data.sent===1?"":"s"}.`)}catch(e){setMessage(pushError(e))}finally{setBusy(false)}}
if(!supported)return <p className="text-xs text-muted-foreground">Este navegador no soporta Web Push.</p>;return <div className="rounded-xl border border-border p-4"><div className="flex items-start gap-3"><BellRing className="mt-0.5 text-primary" size={20}/><div className="flex-1"><strong className="text-sm">Notificaciones del dispositivo</strong><p className="mt-1 text-xs text-muted-foreground">Recibe avisos de mensajes y pedidos aunque MTG Display CR no esté abierto.</p><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void(enabled?disable():enable())} className={`inline-flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-bold disabled:opacity-50 ${enabled?"border border-border text-muted-foreground":"bg-primary text-primary-foreground"}`}>{enabled?<BellOff size={16}/>:<BellRing size={16}/>} {busy?"Procesando…":enabled?"Desactivar en este dispositivo":"Activar notificaciones"}</button>{enabled&&<button disabled={busy} onClick={()=>void testPush()} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm font-bold disabled:opacity-50"><Send size={16}/>Enviar prueba</button>}{!enabled&&showRepair&&<button disabled={busy} onClick={()=>void repair()} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm font-bold disabled:opacity-50"><RefreshCw size={16}/>Reparar notificaciones</button>}</div>{message&&<p className="mt-2 text-xs text-muted-foreground">{message}</p>}</div></div></div>}
