"use client";
import{useEffect,useState}from"react";
import{BellRing,BellOff}from"lucide-react";
import{getSupabase}from"@/lib/supabase";
type Props={userId:string};
function b64(s:string){const p="=".repeat((4-s.length%4)%4),raw=atob((s+p).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
export default function PushNotificationsSettings({userId}:Props){const s=getSupabase();const[supported,setSupported]=useState(true),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{if(!("serviceWorker"in navigator)||!("PushManager"in window)||!("Notification"in window)){setSupported(false);return}void navigator.serviceWorker.register("/push-sw.js").then(()=>navigator.serviceWorker.ready).then(r=>r.pushManager.getSubscription()).then(x=>setEnabled(!!x)).catch(()=>setSupported(false))},[]);
 async function enable(){if(!s)return;setBusy(true);setMessage("");try{const key=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(!key)throw new Error("VAPID public key is not configured");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("Permiso de notificaciones no concedido");const r=await navigator.serviceWorker.ready;let sub=await r.pushManager.getSubscription();if(!sub)sub=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(key)});const j=sub.toJSON(),p256dh=j.keys?.p256dh,auth=j.keys?.auth;if(!p256dh||!auth)throw new Error("El navegador no devolvió las claves Push");const{error}=await s.from("push_subscriptions").upsert({user_id:userId,endpoint:sub.endpoint,p256dh,auth,user_agent:navigator.userAgent,updated_at:new Date().toISOString()},{onConflict:"endpoint"});if(error)throw error;setEnabled(true);setMessage("Notificaciones activadas en este dispositivo.")}catch(e:any){setMessage(e?.message||"No se pudieron activar las notificaciones.")}finally{setBusy(false)}}
 async function disable(){if(!s)return;setBusy(true);setMessage("");try{const r=await navigator.serviceWorker.ready,sub=await r.pushManager.getSubscription();if(sub){await s.from("push_subscriptions").delete().eq("user_id",userId).eq("endpoint",sub.endpoint);await sub.unsubscribe()}setEnabled(false);setMessage("Notificaciones desactivadas en este dispositivo.")}catch(e:any){setMessage(e?.message||"No se pudieron desactivar las notificaciones.")}finally{setBusy(false)}}
 if(!supported)return <p className="text-xs text-muted-foreground">Este navegador no soporta Web Push.</p>;
 return <div className="rounded-xl border border-border p-4"><div className="flex items-start gap-3"><BellRing className="mt-0.5 text-primary" size={20}/><div className="flex-1"><strong className="text-sm">Notificaciones del dispositivo</strong><p className="mt-1 text-xs text-muted-foreground">Recibe avisos de mensajes y pedidos aunque MTG Display CR no esté abierto.</p><button disabled={busy} onClick={()=>void(enabled?disable():enable())} className={`mt-3 inline-flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-bold disabled:opacity-50 ${enabled?"border border-border text-muted-foreground":"bg-primary text-primary-foreground"}`}>{enabled?<BellOff size={16}/>:<BellRing size={16}/>} {busy?"Procesando…":enabled?"Desactivar en este dispositivo":"Activar notificaciones"}</button>{message&&<p className="mt-2 text-xs text-muted-foreground">{message}</p>}</div></div></div>}
