"use client";

import {MapPin,Star,ShoppingBag,X,Store,UserRound,ArrowRight} from "lucide-react";
import StoreIdentityBadges from "@/components/StoreIdentityBadges";

export type PreviewSeller={id:string;public_name:string|null;store_name:string|null;slug:string|null;location:string|null;seller_type:string|null;verification_status:string|null;avatar_key:string|null;rating?:number|null;reviews?:number;sales?:number};

function nameOf(s:PreviewSeller){return s.seller_type==="store"&&s.store_name?.trim()?s.store_name.trim():s.public_name?.trim()||"Seller"}
function Identity({seller,size="lg"}:{seller:PreviewSeller;size?:"sm"|"lg"}){const name=nameOf(seller),cls=size==="lg"?"h-24 w-24 text-3xl":"h-14 w-14 text-lg";if(seller.seller_type!=="store"&&seller.avatar_key)return <img src={`/avatars/${seller.avatar_key}.webp`} alt="" className={`${cls} rounded-full border-2 border-primary/40 object-cover`}/>;return <div className={`grid ${cls} place-items-center rounded-full border-2 border-primary/40 bg-primary/10 font-serif font-black text-primary`}>{name.slice(0,2).toUpperCase()}</div>}

export function SellerCompactIdentity({seller}:{seller:PreviewSeller}){return <Identity seller={seller} size="sm"/>}

export default function SellerProfilePreview({seller,es,onClose}:{seller:PreviewSeller;es:boolean;onClose:()=>void}){const name=nameOf(seller);return <div className="fixed inset-0 z-[180] grid place-items-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section role="dialog" aria-modal="true" aria-label={name} className="w-full max-w-2xl overflow-hidden rounded-[2rem] border border-primary/40 bg-card shadow-2xl"><div className="relative h-28 bg-gradient-to-br from-primary/20 via-background to-background"><button onClick={onClose} className="absolute right-4 top-4 grid h-9 w-9 place-items-center rounded-full border border-border bg-background/80" aria-label={es?"Cerrar":"Close"}><X size={17}/></button></div><div className="px-6 pb-7 sm:px-8"><div className="-mt-12 flex flex-col gap-4 sm:flex-row sm:items-end"><Identity seller={seller}/><div className="min-w-0 flex-1 pb-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-serif text-3xl font-bold">{name}</h2><StoreIdentityBadges sellerType={seller.seller_type} verificationStatus={seller.verification_status} compact/></div><p className="mt-2 text-sm text-muted-foreground"><MapPin size={13} className="mr-1 inline"/>{seller.location||"Costa Rica"}</p></div></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-secondary/60 p-4"><div className="flex items-center gap-2 font-black"><Star size={17}/>{seller.rating!=null?seller.rating.toFixed(1):"—"}</div><p className="mt-1 text-xs text-muted-foreground">{seller.reviews||0} {es?"valoraciones":"reviews"}</p></div><div className="rounded-2xl bg-secondary/60 p-4"><div className="flex items-center gap-2 font-black"><ShoppingBag size={17}/>{seller.sales||0}</div><p className="mt-1 text-xs text-muted-foreground">{es?"ventas completadas":"completed sales"}</p></div></div><div className="mt-6 flex flex-wrap gap-2"><span className="inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-sm font-semibold text-muted-foreground">{seller.seller_type==="store"?<Store size={15}/>:<UserRound size={15}/>} {seller.seller_type==="store"?(es?"Tienda":"Store"):(es?"Vendedor":"Seller")}</span>{seller.slug&&<a href={`/v/${seller.slug}`} className="ml-auto inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-black text-primary-foreground">{es?"Ver catálogo":"View catalog"}<ArrowRight size={16}/></a>}</div></div></section></div>}
