"use client";

import {useMemo,useState} from "react";
import {MapPin,Search} from "lucide-react";
import StoreIdentityBadges from "@/components/StoreIdentityBadges";
import SellerProfilePreview,{SellerCompactIdentity,type PreviewSeller} from "@/components/SellerProfilePreview";

type Seller=PreviewSeller;type Props={sellers:Seller[];es:boolean};
function shuffled<T>(items:T[]){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function displayName(s:Seller){return s.seller_type==="store"&&s.store_name?.trim()?s.store_name.trim():s.public_name?.trim()||"Seller"}

export default function SellerExplorer({sellers,es}:Props){
 const[query,setQuery]=useState(""),[location,setLocation]=useState("all"),[selected,setSelected]=useState<Seller|null>(null);const randomOrder=useMemo(()=>shuffled(sellers),[sellers]);const locations=useMemo(()=>Array.from(new Set(sellers.map(s=>s.location?.trim()).filter((v):v is string=>Boolean(v)))).sort((a,b)=>a.localeCompare(b)),[sellers]);const filtering=query.trim().length>0||location!=="all";
 const filtered=useMemo(()=>{if(!filtering)return randomOrder;const q=query.trim().toLowerCase();return sellers.filter(s=>{const identityText=s.seller_type==="store"?`${es?"tienda":"store"} ${s.verification_status==="verified"?(es?"certificada":"certified"):""}`:"";const matchesQuery=!q||`${displayName(s)} ${s.public_name||""} ${s.location||""} ${identityText}`.toLowerCase().includes(q);return matchesQuery&&(location==="all"||s.location===location)}).sort((a,b)=>displayName(a).localeCompare(displayName(b)))},[es,filtering,location,query,randomOrder,sellers]);const visible=filtered.slice(0,12);
 return <div className="mt-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={es?"Buscar vendedor, tienda o ubicación…":"Search seller, store or location…"} className="h-11 w-full rounded-xl border border-border bg-card pl-9 pr-3 text-sm outline-none transition focus:border-primary"/></label><select value={location} onChange={e=>setLocation(e.target.value)} className="h-11 rounded-xl border border-border bg-card px-3 text-sm font-semibold outline-none transition focus:border-primary"><option value="all">{es?"Todas las ubicaciones":"All locations"}</option>{locations.map(value=><option key={value} value={value}>{value}</option>)}</select></div>{visible.length?<><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{visible.map(s=>{const name=displayName(s);return <button type="button" key={s.id} onClick={()=>setSelected(s)} className="group rounded-3xl border border-border bg-card p-5 text-left transition hover:-translate-y-0.5 hover:border-primary/60"><div className="flex items-start justify-between gap-3"><SellerCompactIdentity seller={s}/><StoreIdentityBadges sellerType={s.seller_type} verificationStatus={s.verification_status} compact/></div><h3 className="mt-4 font-serif text-xl font-bold">{name}</h3><p className="mt-1 text-sm text-muted-foreground"><MapPin className="mr-1 inline" size={12}/>{s.location||"Costa Rica"}</p><p className="mt-4 text-xs font-bold text-primary">{es?"Ver perfil":"View profile"}</p></button>})}</div>{filtered.length>visible.length&&<p className="mt-5 text-center text-xs text-muted-foreground">{es?`${filtered.length-visible.length} vendedores adicionales. Usa la búsqueda o los filtros para encontrarlos.`:`${filtered.length-visible.length} additional sellers. Use search or filters to find them.`}</p>}</>:<div className="mt-5 rounded-2xl border border-border bg-card p-6 text-sm text-muted-foreground">{es?"No encontramos vendedores con esos filtros.":"No sellers match those filters."}</div>}{selected&&<SellerProfilePreview seller={selected} es={es} onClose={()=>setSelected(null)}/>}</div>;
}
