"use client";

import {useEffect,useState} from "react";
import {ImagePlus,Trash2,Upload} from "lucide-react";
import {getSupabase} from "@/lib/supabase";

type Props={userId:string;es:boolean};
export default function StoreLogoUploader({userId,es}:Props){const[store,setStore]=useState(false),[path,setPath]=useState<string|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");const s=getSupabase();
 useEffect(()=>{if(!s)return;void s.from("profiles").select("seller_type,store_logo_path").eq("id",userId).single().then(({data})=>{setStore(data?.seller_type==="store");setPath(data?.store_logo_path||null)})},[s,userId]);
 if(!store)return null;const url=path&&s?s.storage.from("store-logos").getPublicUrl(path).data.publicUrl:null;
 async function upload(file:File){if(!s)return;setNotice("");if(!["image/png","image/jpeg","image/webp"].includes(file.type)){setNotice(es?"Usa PNG, JPG o WebP.":"Use PNG, JPG or WebP.");return}if(file.size>2*1024*1024){setNotice(es?"El archivo debe pesar máximo 2 MB.":"File must be 2 MB or smaller.");return}const img=new Image(),object=URL.createObjectURL(file);img.onload=async()=>{URL.revokeObjectURL(object);if(img.width!==img.height){setNotice(es?"El logo debe ser cuadrado (1:1). Recomendado: 512 × 512 px.":"Logo must be square (1:1). Recommended: 512 × 512 px.");return}setBusy(true);const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg",next=`${userId}/logo.${ext}`;if(path&&path!==next)await s.storage.from("store-logos").remove([path]);const{error}=await s.storage.from("store-logos").upload(next,file,{upsert:true,contentType:file.type});if(error){setNotice(error.message);setBusy(false);return}const{error:db}=await s.from("profiles").update({store_logo_path:next,updated_at:new Date().toISOString()}).eq("id",userId);if(db)setNotice(db.message);else{setPath(next);setNotice(es?"Logo actualizado.":"Logo updated.")}setBusy(false)};img.src=object}
 async function remove(){if(!s||!path)return;setBusy(true);const old=path;const{error}=await s.from("profiles").update({store_logo_path:null,updated_at:new Date().toISOString()}).eq("id",userId);if(!error){await s.storage.from("store-logos").remove([old]);setPath(null);setNotice(es?"Logo eliminado.":"Logo removed.")}else setNotice(error.message);setBusy(false)}
 return <div className="rounded-2xl border border-primary/30 bg-card p-5"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-2xl border border-border bg-background">{url?<img key={path} src={`${url}?v=${encodeURIComponent(path||"")}`} alt="" className="h-full w-full object-contain p-2"/>:<ImagePlus className="text-muted-foreground"/>}</div><div className="min-w-0"><h3 className="font-bold">{es?"Logo de la tienda":"Store logo"}</h3><p className="mt-1 text-sm text-muted-foreground">{es?"Recomendado: 512 × 512 px · formato cuadrado 1:1 · PNG, JPG o WebP · máximo 2 MB.":"Recommended: 512 × 512 px · square 1:1 · PNG, JPG or WebP · maximum 2 MB."}</p><div className="mt-4 flex flex-wrap gap-2"><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-primary-foreground"><Upload size={15}/>{path?(es?"Cambiar logo":"Change logo"):(es?"Subir logo":"Upload logo")}<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.currentTarget.value=""}}/></label>{path&&<button type="button" onClick={()=>void remove()} disabled={busy} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm font-bold"><Trash2 size={15}/>{es?"Eliminar":"Remove"}</button>}</div>{notice&&<p className="mt-3 text-xs text-muted-foreground">{notice}</p>}</div></div></div>}
