type PushSubscriptionTarget={endpoint:string;p256dh:string;auth_key:string};
type PushPayload={title:string;body:string;url:string;tag?:string;icon?:string;badge?:string};

function b64urlDecode(value:string){const normalized=value.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-value.length%4)%4);return Uint8Array.from(atob(normalized),c=>c.charCodeAt(0))}
function b64urlEncode(value:Uint8Array){let binary="";for(const byte of value)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function concat(...parts:Uint8Array[]){const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length}return out}
function utf8(value:string){return new TextEncoder().encode(value)}
function u32(value:number){const out=new Uint8Array(4);new DataView(out.buffer).setUint32(0,value,false);return out}

async function hmac(key:Uint8Array,data:Uint8Array){const cryptoKey=await crypto.subtle.importKey("raw",key,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",cryptoKey,data))}
async function hkdfExtract(salt:Uint8Array,ikm:Uint8Array){return hmac(salt,ikm)}
async function hkdfExpand(prk:Uint8Array,info:Uint8Array,length:number){const out=new Uint8Array(length);let previous=new Uint8Array(0),offset=0,counter=1;while(offset<length){previous=await hmac(prk,concat(previous,info,new Uint8Array([counter++])));const take=Math.min(previous.length,length-offset);out.set(previous.slice(0,take),offset);offset+=take}return out}

async function createVapidJwt(endpoint:string,subject:string,publicKey:string,privateKey:string){const rawPublic=b64urlDecode(publicKey);if(rawPublic.length!==65||rawPublic[0]!==4)throw new Error("Invalid VAPID public key");const x=b64urlEncode(rawPublic.slice(1,33)),y=b64urlEncode(rawPublic.slice(33,65));const key=await crypto.subtle.importKey("jwk",{kty:"EC",crv:"P-256",x,y,d:privateKey,ext:true},{name:"ECDSA",namedCurve:"P-256"},false,["sign"]);const enc=(value:unknown)=>b64urlEncode(utf8(JSON.stringify(value))),unsigned=`${enc({typ:"JWT",alg:"ES256"})}.${enc({aud:new URL(endpoint).origin,exp:Math.floor(Date.now()/1000)+12*60*60,sub:subject})}`,signature=new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key,utf8(unsigned)));return `${unsigned}.${b64urlEncode(signature)}`}

async function encryptPayload(target:PushSubscriptionTarget,payload:PushPayload){const receiverPublic=b64urlDecode(target.p256dh),authSecret=b64urlDecode(target.auth_key);if(receiverPublic.length!==65||receiverPublic[0]!==4)throw new Error("Invalid subscription p256dh");const receiverKey=await crypto.subtle.importKey("raw",receiverPublic,{name:"ECDH",namedCurve:"P-256"},false,[]),senderKeys=await crypto.subtle.generateKey({name:"ECDH",namedCurve:"P-256"},true,["deriveBits"]),senderPublic=new Uint8Array(await crypto.subtle.exportKey("raw",senderKeys.publicKey)),sharedSecret=new Uint8Array(await crypto.subtle.deriveBits({name:"ECDH",public:receiverKey},senderKeys.privateKey,256));const authPrk=await hkdfExtract(authSecret,sharedSecret),ikm=await hkdfExpand(authPrk,concat(utf8("WebPush: info"),new Uint8Array([0]),receiverPublic,senderPublic),32),salt=crypto.getRandomValues(new Uint8Array(16)),prk=await hkdfExtract(salt,ikm),cek=await hkdfExpand(prk,concat(utf8("Content-Encoding: aes128gcm"),new Uint8Array([0])),16),nonce=await hkdfExpand(prk,concat(utf8("Content-Encoding: nonce"),new Uint8Array([0])),12),plain=concat(utf8(JSON.stringify(payload)),new Uint8Array([2])),aesKey=await crypto.subtle.importKey("raw",cek,"AES-GCM",false,["encrypt"]),ciphertext=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv:nonce,tagLength:128},aesKey,plain));return concat(salt,u32(4096),new Uint8Array([senderPublic.length]),senderPublic,ciphertext)}

export async function sendWebPush(target:PushSubscriptionTarget,payload:PushPayload,config:{subject:string;publicKey:string;privateKey:string;ttl?:number}){const [jwt,body]=await Promise.all([createVapidJwt(target.endpoint,config.subject,config.publicKey,config.privateKey),encryptPayload(target,payload)]);return fetch(target.endpoint,{method:"POST",headers:{TTL:String(config.ttl??60),Authorization:`vapid t=${jwt}, k=${config.publicKey}`,"Content-Encoding":"aes128gcm","Content-Type":"application/octet-stream"},body})}
