"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import {BarChart3,Boxes,Search,ShoppingBag,Users} from "lucide-react";
import {getSupabase} from "@/lib/supabase";

type DemandRow={scryfall_id:string;card_name:string;set_code:string;set_name:string|null;collector_number:string|null;image_uri:string|null;finish:string;language:string;condition:string;interested_users:number;requested_copies:number;current_stock:number;context:string;total_rows:number;total_demand_cards:number;total_requested_copies:number;total_zero_stock:number;total_participating_users:number};
const PAGE_SIZE=15;
const contextLabel:Record<string,string>={CONCENTRATED_DEMAND:"DEMANDA CONCENTRADA",NO_STOCK:"SIN OFERTA",LOW_STOCK:"BAJA OFERTA",HIGH_DEMAND:"ALTA DEMANDA",COVERED:"CUBIERTA"};

export default function MarketDemandPage(){
 const s=getSupabase(),router=useRouter(),params=useSearchParams();
 const page=Math.max(1,Number(params.get("page")||1)||1),search=params.get("q")||"",setCode=params.get("set")||"",finish=params.get("finish")||"",stock=params.get("stock")||"",sort=params.get("sort")||"demand";
 const[rows,setRows]=useState<DemandRow[]>([]),[loading,setLoading]=useState(true),[denied,setDenied]=useState(false),[draftSearch,setDraftSearch]=useState(search);
 const load=useCallback(async()=>{if(!s){setLoading(false);return}setLoading(true);setDenied(false);const{data:{user}}=await s.auth.getUser();if(!user){router.replace("/login");return}const{data:profile}=await s.from("profiles").select("seller_type").eq("id",user.id).maybeSingle();if(profile?.seller_type!=="store"){setDenied(true);setLoading(false);return}const{data,error}=await s.rpc("get_store_market_demand",{p_page:page,p_page_size:PAGE_SIZE,p_search:search||null,p_set_code:setCode||null,p_finish:finish||null,p_stock:stock||null,p_sort:sort});if(error){setDenied(/Store account required|Authentication required/i.test(error.message));setRows([])}else setRows((data||[]) as DemandRow[]);setLoading(false)},[s,page,search,setCode,finish,stock,sort,router]);
 useEffect(()=>{void load()},[load]);useEffect(()=>setDraftSearch(search),[search]);
 const metrics=rows[0]||null,totalRows=Number(metrics?.total_rows||0),totalPages=Math.max(1,Math.ceil(totalRows/PAGE_SIZE));
 function navigate(next:Record<string,string|number|null>){const q=new URLSearchParams(params.toString());Object.entries(next).forEach(([k,v])=>{if(v===null||v==="")q.delete(k);else q.set(k,String(v))});router.push(`/market-demand${q.size?`?${q.toString()}`:""}`)}
 function submitSearch(e:React.FormEvent){e.preventDefault();navigate({q:draftSearch.trim()||null,page:1})}
 const pages=useMemo(()=>{const out:(number|string)[]=[];if(totalPages<=7){for(let i=1;i<=totalPages;i++)out.push(i);return out}const candidates=new Set([1,totalPages,page-1,page,page+1].filter(n=>n>=1&&n<=totalPages));let prev=0;for(const n of [...candidates].sort((a,b)=>a-b)){if(prev&&n-prev>1)out.push("…");out.push(n);prev=n}return out},[page,totalPages]);
 if(denied)return <main className="mx-auto max-w-5xl px-4 py-16"><div className="rounded-2xl border border-border bg-card p-8 text-center"><h1 className="font-serif text-3xl font-bold">Demanda del mercado</h1><p className="mt-3 text-muted-foreground">Esta herramienta de inteligencia de mercado está disponible únicamente para cuentas Store.</p><a href="/dashboard" className="mt-6 inline-flex rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground">Volver al dashboard</a></div></main>;
 return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="mb-7"><p className="text-xs font-black uppercase tracking-[.2em] text-primary">Store Intelligence</p><h1 className="mt-2 font-serif text-3xl font-bold sm:text-4xl">Demanda del mercado</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Señales anónimas de demanda por impresión exacta. Se muestran grupos con 3+ compradores o demanda concentrada de 4+ copias. Nunca se revela quién busca la carta.</p></div>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[BarChart3,"Impresiones con demanda",metrics?.total_demand_cards||0],[Boxes,"Copias solicitadas",metrics?.total_requested_copies||0],[ShoppingBag,"Sin oferta visible",metrics?.total_zero_stock||0],[Users,"Usuarios participantes",metrics?.total_participating_users||0]].map(([Icon,label,value])=>{const I=Icon as typeof BarChart3;return <div key={String(label)} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{String(label)}</p><I size={18} className="text-primary"/></div><p className="mt-3 font-serif text-3xl font-bold">{Number(value).toLocaleString("es-CR")}</p></div>})}</section>
  <section className="mt-6 rounded-2xl border border-border bg-card"><div className="border-b border-border p-4"><div className="grid gap-3 lg:grid-cols-[minmax(240px,1fr)_repeat(4,minmax(130px,auto))]"><form onSubmit={submitSearch} className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={17}/><input value={draftSearch} onChange={e=>setDraftSearch(e.target.value)} placeholder="Buscar carta o collector #" className="h-11 w-full rounded-xl border border-border bg-background pl-10 pr-3 text-sm outline-none focus:border-primary"/></form><input value={setCode} onChange={e=>navigate({set:e.target.value||null,page:1})} placeholder="Set (ej. WOT)" className="h-11 rounded-xl border border-border bg-background px-3 text-sm uppercase"/><select value={finish} onChange={e=>navigate({finish:e.target.value||null,page:1})} className="h-11 rounded-xl border border-border bg-background px-3 text-sm"><option value="">Todos los finishes</option><option value="nonfoil">Nonfoil</option><option value="foil">Foil</option><option value="etched">Etched</option></select><select value={stock} onChange={e=>navigate({stock:e.target.value||null,page:1})} className="h-11 rounded-xl border border-border bg-background px-3 text-sm"><option value="">Todo el stock</option><option value="none">Sin oferta</option><option value="low">Baja oferta</option><option value="covered">Cubierta</option></select><select value={sort} onChange={e=>navigate({sort:e.target.value,page:1})} className="h-11 rounded-xl border border-border bg-background px-3 text-sm"><option value="demand">Mayor demanda</option><option value="copies">Más copias</option><option value="stock">Menor stock</option></select></div></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="border-b border-border text-[11px] font-black uppercase tracking-wider text-muted-foreground"><th className="px-5 py-4">Carta / impresión exacta</th><th className="px-4 py-4 text-center">Compradores</th><th className="px-4 py-4 text-center">Copias</th><th className="px-4 py-4 text-center">Stock compatible</th><th className="px-5 py-4">Señal</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="px-5 py-16 text-center text-muted-foreground">Cargando demanda…</td></tr>:rows.length===0?<tr><td colSpan={5} className="px-5 py-16 text-center text-muted-foreground">Todavía no hay señales que superen el umbral de demanda.</td></tr>:rows.map(r=><tr key={`${r.scryfall_id}-${r.finish}-${r.language}-${r.condition}`} className="border-b border-border/70 last:border-0"><td className="px-5 py-4"><div className="flex items-center gap-3">{r.image_uri?<img src={r.image_uri} alt="" className="h-16 w-12 rounded-md object-cover"/>:<div className="h-16 w-12 rounded-md bg-secondary"/>}<div><p className="font-bold">{r.card_name}</p><p className="mt-1 text-xs text-muted-foreground">{r.set_name?`${r.set_name} · `:""}{r.set_code.toUpperCase()} #{r.collector_number||"—"}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{r.finish} · {r.language.toUpperCase()} · {r.condition}</p></div></div></td><td className="px-4 py-4 text-center font-bold">{r.interested_users}</td><td className="px-4 py-4 text-center font-bold">{r.requested_copies}</td><td className="px-4 py-4 text-center font-bold">{r.current_stock}</td><td className="px-5 py-4"><span className={`inline-flex rounded-full border px-3 py-1 text-[10px] font-black tracking-wider ${r.context==="CONCENTRATED_DEMAND"?"border-orange-500/30 bg-orange-500/10 text-orange-400":r.context==="NO_STOCK"?"border-red-500/30 bg-red-500/10 text-red-400":r.context==="LOW_STOCK"?"border-amber-500/30 bg-amber-500/10 text-amber-400":r.context==="HIGH_DEMAND"?"border-primary/30 bg-primary/10 text-primary":"border-emerald-500/30 bg-emerald-500/10 text-emerald-400"}`}>{contextLabel[r.context]||r.context}</span>{r.context==="CONCENTRATED_DEMAND"&&<p className="mt-1 max-w-[180px] text-[10px] text-muted-foreground">Pocas personas solicitan varias copias de esta impresión.</p>}</td></tr>)}</tbody></table></div>
   <div className="flex flex-col items-center justify-between gap-4 border-t border-border px-4 py-4 sm:flex-row"><p className="text-xs text-muted-foreground">{totalRows?`${totalRows} señales visibles · ${PAGE_SIZE} por página`:"Sin señales visibles"}</p><div className="flex flex-wrap items-center justify-center gap-1"><button disabled={page<=1} onClick={()=>navigate({page:page-1})} className="rounded-lg border border-border px-3 py-2 text-xs font-bold disabled:opacity-40">‹ Anterior</button>{pages.map((p,i)=>typeof p==="string"?<span key={`e${i}`} className="px-2 text-muted-foreground">…</span>:<button key={p} onClick={()=>navigate({page:p})} className={`grid h-9 min-w-9 place-items-center rounded-lg border text-xs font-bold ${p===page?"border-primary bg-primary text-primary-foreground":"border-border"}`}>{p}</button>)}<button disabled={page>=totalPages} onClick={()=>navigate({page:page+1})} className="rounded-lg border border-border px-3 py-2 text-xs font-bold disabled:opacity-40">Siguiente ›</button></div></div>
  </section><p className="mt-4 text-center text-xs text-muted-foreground">Cada fila representa una impresión y criterios específicos. Los datos son anónimos y no permiten contactar al comprador.</p></main>
}
