"use client";

import {useEffect,useMemo,useState} from "react";
import {MapPin,Search,ShieldCheck,Star,ShoppingBag} from "lucide-react";
import AppHeader from "@/components/AppHeader";
import StoreIdentityBadges from "@/components/StoreIdentityBadges";
import {getSupabase} from "@/lib/supabase";
import {DEFAULT_LANGUAGE,LANGUAGE_STORAGE_KEY,type Language} from "@/lib/i18n";

type Store={id:string;public_name:string|null;store_name:string|null;slug:string|null;location:string|null;seller_type:string|null;verification_status:string|null};
type Review={seller_id:string;rating:number};
type Sale={seller_id:string};
type StoreRow=Store&{rating:number|null;reviews:number;sales:number};

function nameOf(store:Store){return store.store_name?.trim()||store.public_name?.trim()||"Store"}

export default function CertifiedStoresPage(){
 const[language,setLanguage]=useState<Language>(DEFAULT_LANGUAGE),[stores,setStores]=useState<Store[]>([]),[reviews,setReviews]=useState<Review[]>([]),[sales,setSales]=useState<Sale[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true);const es=language==="es";
 useEffect(()=>{const stored=localStorage.getItem(LANGUAGE_STORAGE_KEY);if(stored==="es"||stored==="en")setLanguage(stored);void load()},[]);
 async function load(){const s=getSupabase();if(!s){setLoading(false);return}const[{data:p},{data:r},{data:o}]=await Promise.all([s.from("profiles").select("id,public_name,store_name,slug,location,seller_type,verification_status").eq("published",true).eq("seller_type","store").eq("verification_status","verified").not("slug","is",null),s.from("order_reviews").select("seller_id,rating"),s.from("orders").select("seller_id").eq("status","completed")]);setStores((p||[]) as Store[]);setReviews((r||[]) as Review[]);setSales((o||[]) as Sale[]);setLoading(false)}
 const rows=useMemo<StoreRow[]>(()=>stores.map(store=>{const rs=reviews.filter(r=>r.seller_id===store.id);const completed=sales.filter(s=>s.seller_id===store.id).length;return{...store,rating:rs.length?rs.reduce((n,r)=>n+Number(r.rating),0)/rs.length:null,reviews:rs.length,sales:completed}}).filter(store=>{const q=query.trim().toLowerCase();return !q||`${nameOf(store)} ${store.location||""}`.toLowerCase().includes(q)}).sort((a,b)=>(b.rating??-1)-(a.rating??-1)||b.reviews-a.reviews||b.sales-a.sales||nameOf(a).localeCompare(nameOf(b))),[stores,reviews,sales,query]);
 return <main className="min-h-screen bg-background text-foreground"><AppHeader currentPath="/certified-stores"/><section className="mx-auto max-w-6xl px-4 py-10"><div className="max-w-3xl"><div className="flex items-center gap-2 text-sm font-black uppercase tracking-[.16em] text-primary"><ShieldCheck size={18}/>{es?"Tiendas certificadas":"Certified Stores"}</div><h1 className="mt-3 font-serif text-4xl sm:text-5xl">{es?"Compra con tiendas verificadas por MTG Display":"Shop with stores verified by MTG Display"}</h1><p className="mt-4 text-muted-foreground">{es?"Directorio de tiendas que han pasado por nuestro proceso de verificación. Las métricas mostradas provienen de pedidos y valoraciones reales dentro de MTG Display.":"Directory of stores that have passed our verification process. Metrics shown come from real orders and reviews inside MTG Display."}</p></div><label className="relative mt-8 block max-w-xl"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={es?"Buscar tienda o ubicación…":"Search store or location…"} className="h-11 w-full rounded-xl border border-border bg-card pl-10 pr-3 text-sm outline-none focus:border-primary"/></label>{loading?<p className="mt-8 text-muted-foreground">{es?"Cargando tiendas…":"Loading stores…"}</p>:rows.length?<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{rows.map(store=><a key={store.id} href={`/v/${store.slug}`} className="rounded-3xl border border-border bg-card p-6 transition hover:border-primary/50"><div className="flex items-start justify-between gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 font-serif text-lg font-bold text-primary">{nameOf(store).slice(0,2).toUpperCase()}</div><StoreIdentityBadges sellerType={store.seller_type} verificationStatus={store.verification_status} compact/></div><h2 className="mt-5 font-serif text-2xl">{nameOf(store)}</h2><p className="mt-1 text-sm text-muted-foreground"><MapPin size={13} className="mr-1 inline"/>{store.location||"Costa Rica"}</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-secondary/60 p-3"><div className="flex items-center gap-1 text-sm font-bold"><Star size={15}/>{store.rating!==null?store.rating.toFixed(1):"—"}</div><p className="mt-1 text-xs text-muted-foreground">{store.reviews} {es?"valoraciones":"reviews"}</p></div><div className="rounded-2xl bg-secondary/60 p-3"><div className="flex items-center gap-1 text-sm font-bold"><ShoppingBag size={15}/>{store.sales}</div><p className="mt-1 text-xs text-muted-foreground">{es?"ventas completadas":"completed sales"}</p></div></div></a>)}</div>:<div className="mt-8 rounded-3xl border border-border bg-card p-8 text-muted-foreground">{es?"No encontramos tiendas certificadas con esa búsqueda.":"No certified stores match that search."}</div>}</section></main>;
}
