"use client";

import {useEffect,useMemo,useState} from "react";
import type {User} from "@supabase/supabase-js";
import {AlertCircle,Clock3,PackageCheck,ShoppingBag} from "lucide-react";
import AppHeader from "@/components/AppHeader";
import {getSupabase,isSupabaseConfigured} from "@/lib/supabase";
import {DEFAULT_LANGUAGE,LANGUAGE_STORAGE_KEY,type Language} from "@/lib/i18n";

type Status="inventory_confirmation"|"preparing_shipment"|"payment_pending"|"payment_submitted"|"paid"|"shipped"|"completed";
type OrderItem={id:number;quantity:number;requested_quantity:number;seller_confirmed_quantity:number|null;unit_price_crc:number;inventory_items:{cards:{name:string;image_uri:string|null}|null}|null};
type Order={id:number;status:Status;customer_name:string|null;created_at:string;subtotal_crc:number|null;shipping_fee_crc:number|null;total_crc:number|null;inventory_changes_pending:boolean;response_required_from:string|null;payment_expires_at:string|null;order_items:OrderItem[]};
const crc=new Intl.NumberFormat("es-CR",{style:"currency",currency:"CRC",maximumFractionDigits:0});
const OPEN:Status[]=["inventory_confirmation","preparing_shipment","payment_pending","payment_submitted","paid","shipped"];
const labels={es:{inventory_confirmation:"Confirmar inventario",preparing_shipment:"Preparar pedido",payment_pending:"Esperando pago",payment_submitted:"Confirmar pago",paid:"Marcar enviado",shipped:"Enviado",completed:"Completado"},en:{inventory_confirmation:"Confirm inventory",preparing_shipment:"Prepare order",payment_pending:"Waiting for payment",payment_submitted:"Confirm payment",paid:"Mark shipped",shipped:"Shipped",completed:"Completed"}} as const;

export default function PendingSalesPage(){
 const supabase=getSupabase(),configured=isSupabaseConfigured();
 const[user,setUser]=useState<User|null>(null),[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[language,setLanguage]=useState<Language>(DEFAULT_LANGUAGE),[now,setNow]=useState(Date.now());
 const es=language==="es";
 useEffect(()=>{const stored=localStorage.getItem(LANGUAGE_STORAGE_KEY);if(stored==="es"||stored==="en")setLanguage(stored);const h=(e:Event)=>{const v=(e as CustomEvent<Language>).detail;if(v==="es"||v==="en")setLanguage(v)};window.addEventListener("mtg-language-change",h);return()=>window.removeEventListener("mtg-language-change",h)},[]);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getUser().then(({data})=>{setUser(data.user);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>data.subscription.unsubscribe()},[supabase]);
 useEffect(()=>{if(!supabase||!user)return;void(async()=>{setLoading(true);const{data,error}=await supabase.from("orders").select("id,status,customer_name,created_at,subtotal_crc,shipping_fee_crc,total_crc,inventory_changes_pending,response_required_from,payment_expires_at,order_items(id,quantity,requested_quantity,seller_confirmed_quantity,unit_price_crc,inventory_items(cards(name,image_uri)))").eq("seller_id",user.id).in("status",OPEN).order("created_at",{ascending:true});if(error)setNotice(error.message);else setOrders((data||[])as unknown as Order[]);setLoading(false)})()},[supabase,user]);
 const actionable=useMemo(()=>orders.filter(o=>o.response_required_from==="seller"&&["inventory_confirmation","preparing_shipment","payment_submitted","paid"].includes(o.status)),[orders]);
 const waitingBuyer=useMemo(()=>orders.filter(o=>o.response_required_from==="buyer"&&["inventory_confirmation","payment_pending","shipped"].includes(o.status)),[orders]);
 const totalCards=useMemo(()=>actionable.reduce((n,o)=>n+o.order_items.reduce((s,i)=>s+(i.seller_confirmed_quantity??i.quantity),0),0),[actionable]);
 function timer(o:Order){if(o.status!=="payment_pending"||!o.payment_expires_at)return null;const ms=Math.max(0,new Date(o.payment_expires_at).getTime()-now);return `${String(Math.floor(ms/60000)).padStart(2,"0")}:${String(Math.floor(ms%60000/1000)).padStart(2,"0")}`}
 function compact(o:Order,waiting=false){const total=Number(o.total_crc??(Number(o.subtotal_crc||0)+Number(o.shipping_fee_crc||0))),label=(es?labels.es:labels.en)[o.status],remaining=timer(o);return <a key={o.id} href={`/orders/${o.id}`} className={`grid grid-cols-[1fr_auto] items-center gap-3 rounded-2xl border bg-card px-4 py-3 transition sm:px-5 ${waiting?"border-border hover:border-primary/40":"border-primary/25 hover:border-primary/60"}`}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong>#{o.id}</strong><span className="truncate text-sm font-semibold">· {o.customer_name||"Customer"}</span><span className={`rounded-full px-2 py-0.5 text-[11px] font-bold ${waiting?"bg-secondary text-muted-foreground":"bg-primary/10 text-primary"}`}>{label}</span></div><div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-muted-foreground">{waiting?<span>{o.status==="shipped"?(es?"Esperando confirmación de recibido":"Waiting for receipt confirmation"):o.status==="payment_pending"?(es?"Esperando comprobante del comprador":"Waiting for buyer payment proof"):(es?"Esperando aprobación del comprador":"Waiting for buyer approval")}</span>:<span>{es?"Tienes una acción pendiente":"You have an action pending"}</span>}{remaining&&<span className="inline-flex items-center gap-1 font-bold text-amber-500"><Clock3 size={12}/>{remaining}</span>}</div></div><div className="flex items-center gap-3"><strong className="hidden whitespace-nowrap font-serif text-lg text-primary sm:block">{crc.format(total)}</strong><span className="whitespace-nowrap rounded-xl border border-border px-3 py-2 text-xs font-bold sm:px-4 sm:text-sm">{es?"Detalles":"Details"}</span></div></a>}
 if(loading)return <main className="grid min-h-screen place-items-center bg-background text-muted-foreground">{es?"Cargando ventas pendientes…":"Loading pending sales…"}</main>;
 if(!configured||!user)return <main className="grid min-h-screen place-items-center bg-background"><a href="/dashboard" className="rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground">{es?"Volver al panel":"Back to Dashboard"}</a></main>;
 return <main className="min-h-screen bg-background text-foreground"><AppHeader currentPath="/pending-sales"/><div className="mx-auto max-w-6xl px-4 py-7 sm:px-5 sm:py-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-primary">{es?"Pedidos del vendedor":"Seller orders"}</p><h1 className="mt-2 font-serif text-4xl font-bold">{es?"Ventas pendientes":"Pending Sales"}</h1><p className="mt-2 text-sm text-muted-foreground">{actionable.length} {es?"pedido(s) que requieren tu atención":"order(s) requiring your attention"} · {totalCards} {es?"carta(s)":"card(s)"}</p></div><a href="/catalog" className="self-start rounded-xl border border-border bg-card px-4 py-2 text-sm font-semibold sm:self-auto">{es?"Volver a Mi catálogo":"Back to My Catalog"}</a></div>
 {notice&&<div className="mt-5 flex gap-2 rounded-2xl border border-border bg-card p-4 text-sm"><AlertCircle size={18} className="text-amber-500"/>{notice}</div>}
 {actionable.length===0?<section className="mt-7 rounded-3xl border border-border bg-card p-8 text-center"><ShoppingBag className="mx-auto text-muted-foreground" size={36}/><h2 className="mt-3 text-lg font-semibold">{es?"No tienes ventas que requieran una acción":"No sales require your action"}</h2></section>:<section className="mt-7"><div className="mb-3 flex items-center gap-2"><PackageCheck size={17} className="text-primary"/><p className="text-xs font-black uppercase tracking-[.15em] text-primary">{es?"Requieren tu atención":"Requires your attention"} ({actionable.length})</p></div><div className="space-y-2">{actionable.map(o=>compact(o))}</div></section>}
 {waitingBuyer.length>0&&<section className="mt-8"><div className="mb-3"><p className="text-xs font-black uppercase tracking-[.15em] text-muted-foreground">{es?"Esperando al comprador":"Waiting for buyer"} ({waitingBuyer.length})</p><p className="mt-1 text-xs text-muted-foreground">{es?"No requieren ninguna acción tuya por ahora.":"No seller action is required right now."}</p></div><div className="space-y-2">{waitingBuyer.map(o=>compact(o,true))}</div></section>}
 </div></main>
}
