-- Wishlist W1 foundation.
-- A wishlist item targets one exact Scryfall printing plus finish/language/condition.
-- Matching and availability notifications are implemented in later phases.

create table if not exists public.wishlist_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  scryfall_id text not null,
  oracle_id text,
  card_name text not null,
  set_code text not null,
  set_name text not null,
  collector_number text not null,
  image_uri text,
  finish text not null default 'nonfoil',
  language text not null default 'en',
  condition text not null default 'NM',
  quantity_wanted integer not null default 1,
  notifications_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint wishlist_items_quantity_check check (quantity_wanted between 1 and 999),
  constraint wishlist_items_finish_check check (finish in ('nonfoil','foil','etched','surgefoil')),
  constraint wishlist_items_condition_check check (condition in ('NM','EX','VG','G','PL','PO')),
  constraint wishlist_items_language_check check (language in ('en','es','ja','fr','de','it','pt','ko','ru','zhs','zht')),
  constraint wishlist_items_exact_target_unique unique (user_id,scryfall_id,finish,language,condition)
);

create index if not exists wishlist_items_user_id_idx on public.wishlist_items(user_id);
create index if not exists wishlist_items_scryfall_match_idx on public.wishlist_items(scryfall_id,finish,language,condition);
create index if not exists wishlist_items_oracle_id_idx on public.wishlist_items(oracle_id) where oracle_id is not null;

alter table public.wishlist_items enable row level security;

drop policy if exists "wishlist_select_own" on public.wishlist_items;
create policy "wishlist_select_own"
on public.wishlist_items for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "wishlist_insert_own" on public.wishlist_items;
create policy "wishlist_insert_own"
on public.wishlist_items for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "wishlist_update_own" on public.wishlist_items;
create policy "wishlist_update_own"
on public.wishlist_items for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "wishlist_delete_own" on public.wishlist_items;
create policy "wishlist_delete_own"
on public.wishlist_items for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.touch_wishlist_item_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists wishlist_items_touch_updated_at on public.wishlist_items;
create trigger wishlist_items_touch_updated_at
before update on public.wishlist_items
for each row execute function public.touch_wishlist_item_updated_at();
