-- Seller binders for inventory organization.
-- Trade Binder is the immutable system default for each seller.

create table if not exists public.binders (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  is_default boolean not null default false,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint binders_name_not_blank check (length(trim(name)) between 1 and 80)
);

create unique index if not exists binders_one_default_per_seller
  on public.binders(seller_id) where is_default;
create unique index if not exists binders_unique_name_per_seller
  on public.binders(seller_id, lower(name));

alter table public.inventory_items
  add column if not exists binder_id bigint references public.binders(id) on delete restrict;

alter table public.binders enable row level security;

drop policy if exists "sellers manage own binders" on public.binders;
create policy "sellers manage own binders"
on public.binders for all to authenticated
using (seller_id = auth.uid())
with check (seller_id = auth.uid());

drop policy if exists "public read public binders" on public.binders;
create policy "public read public binders"
on public.binders for select to anon, authenticated
using (is_public = true);

create or replace function public.ensure_trade_binder(p_seller_id uuid)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare v_id bigint;
begin
  select id into v_id from public.binders where seller_id=p_seller_id and is_default limit 1;
  if v_id is null then
    insert into public.binders(seller_id,name,is_default,is_public)
    values(p_seller_id,'Trade Binder',true,true)
    on conflict do nothing;
    select id into v_id from public.binders where seller_id=p_seller_id and is_default limit 1;
  end if;
  return v_id;
end;
$$;

-- Existing sellers receive Trade Binder and existing inventory is assigned to it.
insert into public.binders(seller_id,name,is_default,is_public)
select distinct ii.seller_id,'Trade Binder',true,true
from public.inventory_items ii
where not exists (
  select 1 from public.binders b where b.seller_id=ii.seller_id and b.is_default
)
on conflict do nothing;

update public.inventory_items ii
set binder_id=b.id
from public.binders b
where ii.binder_id is null and b.seller_id=ii.seller_id and b.is_default;

create or replace function public.assign_default_binder()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.binder_id is null then new.binder_id := public.ensure_trade_binder(new.seller_id); end if;
  return new;
end;
$$;

drop trigger if exists trg_assign_default_binder on public.inventory_items;
create trigger trg_assign_default_binder
before insert on public.inventory_items
for each row execute function public.assign_default_binder();

create or replace function public.protect_default_binder()
returns trigger language plpgsql set search_path=public as $$
begin
  if tg_op='DELETE' and old.is_default then raise exception 'DEFAULT_BINDER_CANNOT_BE_DELETED'; end if;
  if tg_op='UPDATE' and old.is_default and (new.name is distinct from old.name or new.is_default is distinct from old.is_default) then
    raise exception 'DEFAULT_BINDER_CANNOT_BE_RENAMED';
  end if;
  return case when tg_op='DELETE' then old else new end;
end;
$$;

drop trigger if exists trg_protect_default_binder on public.binders;
create trigger trg_protect_default_binder
before update or delete on public.binders
for each row execute function public.protect_default_binder();

-- Safely delete a custom binder by moving its cards back to Trade Binder first.
create or replace function public.delete_binder(p_binder_id bigint)
returns void language plpgsql security definer set search_path=public as $$
declare v_binder public.binders%rowtype; v_default bigint;
begin
  select * into v_binder from public.binders where id=p_binder_id for update;
  if not found then raise exception 'BINDER_NOT_FOUND'; end if;
  if v_binder.seller_id<>auth.uid() then raise exception 'BINDER_ACCESS_DENIED'; end if;
  if v_binder.is_default then raise exception 'DEFAULT_BINDER_CANNOT_BE_DELETED'; end if;
  v_default:=public.ensure_trade_binder(v_binder.seller_id);
  update public.inventory_items set binder_id=v_default,updated_at=now() where binder_id=p_binder_id;
  delete from public.binders where id=p_binder_id;
end;
$$;
