-- P1.1 — Global Card Kingdom price cache
-- Independent from public.cards so CK prices can exist before a printing is added locally.

create table if not exists public.cardkingdom_price_cache (
  id bigint generated by default as identity primary key,
  scryfall_id uuid not null,
  finish text not null,
  condition text not null,
  price_usd numeric(10,2) not null,
  updated_at timestamptz not null default now(),

  constraint cardkingdom_price_cache_finish_check
    check (finish in ('nonfoil','foil','etched','surgefoil')),

  constraint cardkingdom_price_cache_condition_check
    check (condition in ('NM','EX','VG','G')),

  constraint cardkingdom_price_cache_price_check
    check (price_usd >= 0),

  constraint cardkingdom_price_cache_unique_price
    unique (scryfall_id, finish, condition)
);

create index if not exists cardkingdom_price_cache_lookup_idx
  on public.cardkingdom_price_cache (scryfall_id, finish, condition);

create index if not exists cardkingdom_price_cache_updated_at_idx
  on public.cardkingdom_price_cache (updated_at);

alter table public.cardkingdom_price_cache enable row level security;

drop policy if exists "Authenticated users can read Card Kingdom price cache"
  on public.cardkingdom_price_cache;

create policy "Authenticated users can read Card Kingdom price cache"
  on public.cardkingdom_price_cache
  for select
  to authenticated
  using (true);

revoke insert, update, delete
  on public.cardkingdom_price_cache
  from anon, authenticated;

grant select
  on public.cardkingdom_price_cache
  to authenticated;
