-- Notifications v1
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id bigint references public.orders(id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  href text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);
create index if not exists notifications_user_unread_idx on public.notifications(user_id, read_at) where read_at is null;

alter table public.notifications enable row level security;

drop policy if exists notifications_select_own on public.notifications;
create policy notifications_select_own on public.notifications for select to authenticated using (auth.uid() = user_id);
drop policy if exists notifications_update_own on public.notifications;
create policy notifications_update_own on public.notifications for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.create_order_notification()
returns trigger language plpgsql security definer set search_path='' as $$
declare
  v_buyer uuid;
  v_seller uuid;
  v_target uuid;
  v_title text;
  v_body text;
  v_type text;
begin
  if tg_table_name = 'order_messages' then
    select buyer_id,seller_id into v_buyer,v_seller from public.orders where id=new.order_id;
    v_target := case when new.sender_id=v_buyer then v_seller else v_buyer end;
    v_type := 'message'; v_title := 'Nuevo mensaje'; v_body := left(new.message,180);
  elsif tg_table_name = 'orders' then
    v_buyer:=new.buyer_id; v_seller:=new.seller_id;
    if tg_op='INSERT' then
      v_target:=v_seller; v_type:='new_order'; v_title:='Nuevo pedido'; v_body:='Tienes un nuevo pedido por revisar.';
    elsif old.status is distinct from new.status then
      if new.status='payment_pending' then v_target:=v_buyer; v_type:='payment_requested'; v_title:='Pago solicitado'; v_body:='El vendedor está esperando tu pago.';
      elsif new.status='payment_submitted' then v_target:=v_seller; v_type:='payment_submitted'; v_title:='Comprobante recibido'; v_body:='El comprador envió su comprobante de pago.';
      elsif new.status='paid' then v_target:=v_buyer; v_type:='payment_confirmed'; v_title:='Pago confirmado'; v_body:='El vendedor confirmó tu pago.';
      elsif new.status='shipped' then v_target:=v_buyer; v_type:='shipped'; v_title:='Pedido enviado'; v_body:='Tu pedido fue marcado como enviado.';
      elsif new.status='completed' then v_target:=v_seller; v_type:='completed'; v_title:='Pedido recibido'; v_body:='El comprador confirmó que recibió el pedido.';
      elsif new.status='cancelled' then
        v_type:='cancelled'; v_title:='Pedido cancelado'; v_body:='El pedido fue cancelado.';
        v_target:=case when auth.uid()=v_buyer then v_seller else v_buyer end;
      end if;
    elsif old.response_required_from is distinct from new.response_required_from and new.response_required_from is not null then
      v_target:=case when new.response_required_from='seller' then v_seller else v_buyer end;
      v_type:='action_required'; v_title:='Acción requerida'; v_body:='Este pedido necesita tu respuesta.';
    end if;
  end if;

  if v_target is not null and v_type is not null then
    insert into public.notifications(user_id,order_id,type,title,body,href)
    values(v_target,case when tg_table_name='orders' then new.id else new.order_id end,v_type,v_title,v_body,'/orders/'||(case when tg_table_name='orders' then new.id else new.order_id end)::text);
  end if;
  return new;
end $$;

drop trigger if exists notifications_order_message on public.order_messages;
create trigger notifications_order_message after insert on public.order_messages for each row execute function public.create_order_notification();
drop trigger if exists notifications_order_change on public.orders;
create trigger notifications_order_change after insert or update on public.orders for each row execute function public.create_order_notification();

comment on table public.notifications is 'In-app notifications for Display.cr Notifications v1.';
