-- MTG Display CR
-- The prepared-package photo is the shipment evidence; no second shipment upload is required.
-- Adds one buyer review per completed order.

create table if not exists public.order_reviews (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  buyer_id uuid not null references public.profiles(id) on delete restrict,
  seller_id uuid not null references public.profiles(id) on delete restrict,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint order_reviews_comment_length check (comment is null or char_length(comment) <= 1000)
);

alter table public.order_reviews enable row level security;

drop policy if exists "reviews are publicly readable" on public.order_reviews;
create policy "reviews are publicly readable"
on public.order_reviews for select
using (true);

drop policy if exists "buyers create completed order reviews" on public.order_reviews;
create policy "buyers create completed order reviews"
on public.order_reviews for insert
to authenticated
with check (
  buyer_id = auth.uid()
  and exists (
    select 1 from public.orders o
    where o.id = order_id
      and o.buyer_id = auth.uid()
      and o.seller_id = seller_id
      and o.status = 'completed'
  )
);

-- Use an RPC for the actual write so buyer/seller/order IDs cannot be mixed.
create or replace function public.submit_order_review(
  p_order_id bigint,
  p_rating integer,
  p_comment text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_order public.orders%rowtype;
  v_review_id bigint;
begin
  if v_user is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_rating < 1 or p_rating > 5 then raise exception 'INVALID_RATING'; end if;
  if p_comment is not null and char_length(btrim(p_comment)) > 1000 then raise exception 'REVIEW_TOO_LONG'; end if;

  select * into v_order from public.orders where id = p_order_id;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  if v_order.buyer_id <> v_user then raise exception 'ORDER_ACCESS_DENIED'; end if;
  if v_order.status <> 'completed' then raise exception 'ORDER_NOT_COMPLETED'; end if;
  if exists(select 1 from public.order_reviews r where r.order_id = p_order_id) then raise exception 'ORDER_ALREADY_REVIEWED'; end if;

  insert into public.order_reviews(order_id,buyer_id,seller_id,rating,comment)
  values(p_order_id,v_user,v_order.seller_id,p_rating,nullif(btrim(p_comment),''))
  returning id into v_review_id;

  insert into public.order_events(order_id,actor_id,actor_role,event_type,message)
  values(p_order_id,v_user,'buyer','seller_review_submitted','Buyer submitted a seller review.');

  return v_review_id;
end;
$$;

-- Final seller action: once payment is verified, the package photo already on file
-- serves as evidence. The order becomes shipped immediately; no second photo is needed.
create or replace function public.advance_order_status(p_order_id bigint,p_action text)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare
  v_user_id uuid:=auth.uid();
  v_order public.orders%rowtype;
  v_new_status text;
  v_role text;
  v_event_type text;
  v_message text;
begin
  if v_user_id is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;

  if v_user_id=v_order.seller_id then v_role:='seller';
  elsif v_user_id=v_order.buyer_id then v_role:='buyer';
  else raise exception 'ORDER_ACCESS_DENIED';
  end if;

  case p_action
    when 'confirm_payment' then
      if v_role<>'seller' or v_order.status<>'payment_submitted' then raise exception 'INVALID_ORDER_ACTION'; end if;
      if not exists(
        select 1 from public.order_attachments a
        where a.order_id=p_order_id
          and a.uploaded_by=v_order.buyer_id
          and a.attachment_type='payment_proof'
      ) then raise exception 'PAYMENT_PROOF_REQUIRED'; end if;
      if not exists(
        select 1 from public.order_attachments a
        where a.order_id=p_order_id
          and a.uploaded_by=v_order.seller_id
          and a.attachment_type='package_proof'
      ) then raise exception 'PACKAGE_PROOF_REQUIRED'; end if;
      v_new_status:='shipped';
      v_event_type:='payment_confirmed_and_shipped';
      v_message:='Seller confirmed payment. Prepared-package evidence is on file and the order was marked as shipped.';

    when 'mark_shipped' then
      -- Compatibility for any order that may already be in paid during rollout.
      if v_role<>'seller' or v_order.status<>'paid' then raise exception 'INVALID_ORDER_ACTION'; end if;
      if not exists(
        select 1 from public.order_attachments a
        where a.order_id=p_order_id
          and a.uploaded_by=v_order.seller_id
          and a.attachment_type='package_proof'
      ) then raise exception 'PACKAGE_PROOF_REQUIRED'; end if;
      v_new_status:='shipped';
      v_event_type:='order_shipped';
      v_message:='Seller marked the order as shipped using the prepared-package evidence already on file.';

    when 'confirm_received' then
      if v_role<>'buyer' or v_order.status<>'shipped' then raise exception 'INVALID_ORDER_ACTION'; end if;
      v_new_status:='completed';
      v_event_type:='order_completed';
      v_message:='Buyer confirmed receipt. Order completed and seller review is now available.';

    else
      raise exception 'UNKNOWN_ORDER_ACTION';
  end case;

  update public.orders
  set status=v_new_status,
      payment_confirmed_at=case when p_action='confirm_payment' then now() else payment_confirmed_at end,
      shipped_at=case when p_action in ('confirm_payment','mark_shipped') then now() else shipped_at end,
      response_required_from=case when p_action in ('confirm_payment','mark_shipped') then 'buyer' when p_action='confirm_received' then null else response_required_from end,
      response_required_at=case when p_action in ('confirm_payment','mark_shipped') then now() when p_action='confirm_received' then null else response_required_at end,
      updated_at=now()
  where id=p_order_id;

  insert into public.order_events(order_id,actor_id,actor_role,event_type,message)
  values(p_order_id,v_user_id,v_role,v_event_type,v_message);

  return v_new_status;
end;
$$;

revoke all on function public.submit_order_review(bigint,integer,text) from public;
grant execute on function public.submit_order_review(bigint,integer,text) to authenticated;
grant execute on function public.advance_order_status(bigint,text) to authenticated;
