-- Checkout v2 foundation: atomic inventory reservations.
-- Physical inventory is only deducted after seller confirms payment.

create table if not exists public.inventory_reservations (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  inventory_item_id bigint not null references public.inventory_items(id) on delete restrict,
  buyer_id uuid not null references public.profiles(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  status text not null default 'active' check (status in ('active','consumed','released','expired')),
  reserved_at timestamptz not null default now(),
  consumed_at timestamptz,
  released_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(order_id, inventory_item_id)
);

create index if not exists inventory_reservations_active_item_idx
  on public.inventory_reservations(inventory_item_id)
  where status='active';
create index if not exists inventory_reservations_order_idx
  on public.inventory_reservations(order_id);

alter table public.inventory_reservations enable row level security;

-- Availability helper used by catalog/cart work: physical stock minus active reservations.
create or replace function public.inventory_available_quantity(p_inventory_item_id bigint)
returns integer
language sql
stable
security definer
set search_path=public
as $$
  select greatest(
    coalesce(i.quantity,0) - coalesce((
      select sum(r.quantity)::integer
      from public.inventory_reservations r
      where r.inventory_item_id=i.id and r.status='active'
    ),0),
    0
  )::integer
  from public.inventory_items i
  where i.id=p_inventory_item_id;
$$;

grant execute on function public.inventory_available_quantity(bigint) to anon, authenticated;

-- Replace checkout RPC so order creation and reservation happen in one transaction.
create or replace function public.create_checkout_order(
  p_seller_id uuid,
  p_delivery_point_id bigint,
  p_items jsonb,
  p_customer_note text default null::text
)
returns bigint
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_buyer_id uuid := auth.uid();
  v_order_id bigint;
  v_buyer public.profiles%rowtype;
  v_seller public.profiles%rowtype;
  v_point public.delivery_points%rowtype;
  v_item jsonb;
  v_inventory public.inventory_items%rowtype;
  v_qty integer;
  v_reserved integer;
  v_available integer;
  v_price_usd numeric;
  v_unit_price numeric;
  v_usd_to_crc numeric := 520;
  v_discount numeric := 20;
  v_shipping_fee numeric := 600;
  v_subtotal numeric := 0;
  v_total numeric := 0;
  v_finish text;
  v_condition text;
begin
  if v_buyer_id is null then raise exception 'AUTH_REQUIRED'; end if;
  if v_buyer_id = p_seller_id then raise exception 'OWN_CATALOG'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'CART_EMPTY'; end if;

  select * into v_buyer from public.profiles where id=v_buyer_id;
  if not found then raise exception 'BUYER_PROFILE_REQUIRED'; end if;
  if nullif(btrim(v_buyer.public_name),'') is null then raise exception 'BUYER_NAME_REQUIRED'; end if;
  if nullif(btrim(v_buyer.whatsapp),'') is null then raise exception 'BUYER_WHATSAPP_REQUIRED'; end if;
  if not exists(select 1 from public.profile_delivery_points x where x.profile_id=v_buyer_id and x.role='buyer_pickup') then raise exception 'BUYER_PICKUP_REQUIRED'; end if;

  select * into v_seller from public.profiles where id=p_seller_id and published=true;
  if not found then raise exception 'SELLER_UNAVAILABLE'; end if;
  if nullif(btrim(v_seller.public_name),'') is null then raise exception 'SELLER_NAME_REQUIRED'; end if;
  if nullif(btrim(v_seller.whatsapp),'') is null then raise exception 'SELLER_WHATSAPP_REQUIRED'; end if;
  if nullif(btrim(v_seller.sinpe_mobile),'') is null then raise exception 'SELLER_SINPE_REQUIRED'; end if;
  if not exists(select 1 from public.profile_delivery_points x where x.profile_id=p_seller_id and x.role='seller_dropoff') then raise exception 'SELLER_DROPOFF_REQUIRED'; end if;

  select dp.* into v_point from public.delivery_points dp
  where dp.id=p_delivery_point_id and dp.active=true
    and exists(select 1 from public.profile_delivery_points x where x.profile_id=v_buyer_id and x.delivery_point_id=dp.id and x.role='buyer_pickup')
    and exists(select 1 from public.profile_delivery_points x where x.profile_id=p_seller_id and x.delivery_point_id=dp.id and x.role='seller_dropoff');
  if not found then raise exception 'DELIVERY_POINT_NOT_SHARED'; end if;

  select coalesce(usd_to_crc,520),coalesce(discount_percent,20),coalesce(shipping_fee_crc,600)
    into v_usd_to_crc,v_discount,v_shipping_fee
  from public.seller_pricing_settings where seller_id=p_seller_id;
  v_shipping_fee:=greatest(coalesce(v_shipping_fee,600),0);

  insert into public.orders(seller_id,buyer_id,buyer_email,customer_name,customer_phone,customer_note,status,delivery_point_id,delivery_store_name,delivery_location_name,sinpe_phone_snapshot,subtotal_crc,shipping_fee_crc,total_crc,created_at,updated_at)
  values(p_seller_id,v_buyer_id,auth.jwt()->>'email',v_buyer.public_name,v_buyer.whatsapp,nullif(btrim(p_customer_note),''),'inventory_confirmation',v_point.id,v_point.store_name,v_point.location_name,v_seller.sinpe_mobile,0,v_shipping_fee,v_shipping_fee,now(),now())
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty:=greatest(0,coalesce((v_item->>'quantity')::integer,0));
    if v_qty<1 then raise exception 'INVALID_QUANTITY'; end if;

    -- Row lock serializes competing checkout attempts for this inventory item.
    select * into v_inventory from public.inventory_items
    where id=(v_item->>'inventory_item_id')::bigint and seller_id=p_seller_id and available=true
    for update;
    if not found then raise exception 'ITEM_UNAVAILABLE'; end if;

    select coalesce(sum(r.quantity),0)::integer into v_reserved
    from public.inventory_reservations r
    where r.inventory_item_id=v_inventory.id and r.status='active';
    v_available:=greatest(v_inventory.quantity-v_reserved,0);
    if v_available<v_qty then raise exception 'ITEM_RESERVED_OR_UNAVAILABLE'; end if;

    v_finish:=lower(regexp_replace(btrim(v_inventory.finish),'[ _-]+','','g'));
    if v_finish='normal' then v_finish:='nonfoil'; end if;
    v_condition:=upper(btrim(v_inventory.condition));
    if v_inventory.pricing_mode='custom' then v_unit_price:=v_inventory.custom_price_crc;
    else
      v_price_usd:=null;
      select cp.price_usd into v_price_usd from public.card_prices cp
      where cp.scryfall_id=v_inventory.scryfall_id and cp.source='cardkingdom'
        and lower(regexp_replace(btrim(cp.finish),'[ _-]+','','g'))=v_finish
        and upper(btrim(cp.condition))=v_condition limit 1;
      if v_price_usd is null then raise exception 'PRICE_UNAVAILABLE'; end if;
      v_unit_price:=round(v_price_usd*v_usd_to_crc);
      if v_inventory.pricing_mode='discount' then v_unit_price:=round(v_unit_price*(1-v_discount/100)); end if;
    end if;
    if v_unit_price is null then raise exception 'PRICE_UNAVAILABLE'; end if;

    insert into public.order_items(order_id,inventory_item_id,quantity,requested_quantity,unit_price_crc,pricing_mode,finish,condition,language)
    values(v_order_id,v_inventory.id,v_qty,v_qty,v_unit_price,v_inventory.pricing_mode,v_inventory.finish,v_inventory.condition,v_inventory.language);

    insert into public.inventory_reservations(order_id,inventory_item_id,buyer_id,seller_id,quantity,status)
    values(v_order_id,v_inventory.id,v_buyer_id,p_seller_id,v_qty,'active');

    v_subtotal:=v_subtotal+(v_unit_price*v_qty);
  end loop;

  v_total:=v_subtotal+v_shipping_fee;
  update public.orders set subtotal_crc=v_subtotal,shipping_fee_crc=v_shipping_fee,total_crc=v_total,updated_at=now() where id=v_order_id;
  insert into public.order_events(order_id,actor_id,actor_role,event_type,message)
  values(v_order_id,v_buyer_id,'buyer','order_created','Buyer submitted checkout; requested inventory was reserved');
  return v_order_id;
end;
$function$;

grant execute on function public.create_checkout_order(uuid,bigint,jsonb,text) to authenticated;

-- Extend current order transition RPC: confirmed payment consumes reservation and physical stock together.
create or replace function public.advance_order_status(p_order_id bigint,p_action text)
returns text language plpgsql security definer set search_path=public as $$
declare
  v_user_id uuid:=auth.uid();
  v_order public.orders%rowtype;
  v_new_status text;
  v_role text;
  v_event_type text;
  v_message text;
  v_item record;
  v_inventory public.inventory_items%rowtype;
begin
  if v_user_id is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  if v_user_id=v_order.seller_id then v_role:='seller'; elsif v_user_id=v_order.buyer_id then v_role:='buyer'; else raise exception 'ORDER_ACCESS_DENIED'; end if;

  case p_action
    when 'confirm_payment' then
      if v_role<>'seller' or v_order.status<>'payment_submitted' then raise exception 'INVALID_ORDER_ACTION'; end if;
      if not exists(select 1 from public.order_attachments a where a.order_id=p_order_id and a.uploaded_by=v_order.buyer_id and a.attachment_type='payment_proof') then raise exception 'PAYMENT_PROOF_REQUIRED'; end if;

      for v_item in
        select r.inventory_item_id,sum(r.quantity)::integer sold_quantity
        from public.inventory_reservations r where r.order_id=p_order_id and r.status='active'
        group by r.inventory_item_id order by r.inventory_item_id
      loop
        select * into v_inventory from public.inventory_items where id=v_item.inventory_item_id for update;
        if not found then raise exception 'INVENTORY_ITEM_NOT_FOUND'; end if;
        if v_inventory.seller_id<>v_order.seller_id then raise exception 'INVENTORY_SELLER_MISMATCH'; end if;
        if v_inventory.quantity<v_item.sold_quantity then raise exception 'INSUFFICIENT_INVENTORY'; end if;
      end loop;
      if not exists(select 1 from public.inventory_reservations r where r.order_id=p_order_id and r.status='active') then raise exception 'ACTIVE_RESERVATION_REQUIRED'; end if;

      for v_item in
        select r.inventory_item_id,sum(r.quantity)::integer sold_quantity
        from public.inventory_reservations r where r.order_id=p_order_id and r.status='active'
        group by r.inventory_item_id order by r.inventory_item_id
      loop
        update public.inventory_items set quantity=quantity-v_item.sold_quantity,
          available=case when quantity-v_item.sold_quantity<=0 then false else available end,updated_at=now()
        where id=v_item.inventory_item_id;
      end loop;
      update public.inventory_reservations set status='consumed',consumed_at=now(),updated_at=now()
      where order_id=p_order_id and status='active';
      v_new_status:='paid';v_event_type:='payment_confirmed';v_message:='Seller confirmed payment. Reserved inventory was sold and deducted.';

    when 'mark_shipped' then
      if v_role<>'seller' or v_order.status<>'paid' then raise exception 'INVALID_ORDER_ACTION'; end if;
      if not exists(select 1 from public.order_attachments a where a.order_id=p_order_id and a.uploaded_by=v_order.seller_id and a.attachment_type='shipment_proof') then raise exception 'SHIPMENT_PROOF_REQUIRED'; end if;
      v_new_status:='shipped';v_event_type:='order_shipped';v_message:='Seller marked the paid order as shipped/delivered.';

    when 'confirm_received' then
      if v_role<>'buyer' or v_order.status<>'shipped' then raise exception 'INVALID_ORDER_ACTION'; end if;
      v_new_status:='completed';v_event_type:='order_completed';v_message:='Buyer confirmed receipt. Order completed.';
    else raise exception 'UNKNOWN_ORDER_ACTION';
  end case;

  update public.orders set status=v_new_status,
    payment_confirmed_at=case when p_action='confirm_payment' then now() else payment_confirmed_at end,
    shipped_at=case when p_action='mark_shipped' then now() else shipped_at end,
    completed_at=case when p_action='confirm_received' then now() else completed_at end,
    response_required_from=case when p_action='confirm_payment' then 'buyer' when p_action='mark_shipped' then 'buyer' when p_action='confirm_received' then null else response_required_from end,
    response_required_at=case when p_action in ('confirm_payment','mark_shipped') then now() when p_action='confirm_received' then null else response_required_at end,
    updated_at=now() where id=p_order_id;
  insert into public.order_events(order_id,actor_id,actor_role,event_type,message) values(p_order_id,v_user_id,v_role,v_event_type,v_message);
  return v_new_status;
end;$$;

grant execute on function public.advance_order_status(bigint,text) to authenticated;

-- Explicit release primitive for the upcoming cancellation/expiry state-machine work.
create or replace function public.release_order_reservations(p_order_id bigint,p_reason text default 'cancelled')
returns integer language plpgsql security definer set search_path=public as $$
declare v_user_id uuid:=auth.uid();v_order public.orders%rowtype;v_count integer;
begin
  if v_user_id is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  if v_user_id<>v_order.buyer_id and v_user_id<>v_order.seller_id then raise exception 'ORDER_ACCESS_DENIED'; end if;
  update public.inventory_reservations set status='released',released_at=now(),updated_at=now()
  where order_id=p_order_id and status='active';
  get diagnostics v_count=row_count;
  if v_count>0 then insert into public.order_events(order_id,actor_id,actor_role,event_type,message)
    values(p_order_id,v_user_id,case when v_user_id=v_order.seller_id then 'seller' else 'buyer' end,'inventory_released','Inventory reservation released: '||coalesce(nullif(btrim(p_reason),''),'cancelled')); end if;
  return v_count;
end;$$;

grant execute on function public.release_order_reservations(bigint,text) to authenticated;
